### ISSUE TITLE
Update doesn't work or version is not updated to 3.4.10

### ISSUE THREAD

**Issue by vDorst** [JC5/firefly-iii#100]
I was trying to upgrade 3.4.9 to 3.4.10

I run this command multipule times. So this is the output of the last one.
```
root@server:/data/webapps/firefly-iii# php ../composer.phar update --no-dev
Loading composer repositories with package information
Updating dependencies
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
```

But Version 3.4.9 is shown on the front page even after restart apache2.

**Comment by JC5** [comment]
Sadly, upgrading will probably not work.

I've been trying to get composer to play nice, but I cannot get it to upgrade "itself" when installed as a project. I've updated the installation instructions to reflect this.

What you should do (sorry):

* Backup your database.
* Backup ``firefly-iii/.env``
* Backup ``firefly-iii/storage/upload``

Run the installation again using [these instructions](https://github.com/JC5/firefly-iii/wiki/Installation). Then you'll have the latest version. To get the latest database, run

``php artisan migrate``

That should get you the latest version.

**Comment by vDorst** [comment]
This did the trick. Thanks.
