### ISSUE TITLE
Problem with paying bills

### ISSUE THREAD

**Issue by iwan41** [JC5/firefly-iii#101]
Hi,

I was unable to find how paying bills works. 
For example, I've created bill for 432 euro and in this month I would like to pay this bill (monthly bill to be precise). There is no wiki for bills section.

Could you help me with this?

Another question is that if you don't mind if I prepare translation for your project?

**Comment by JC5** [comment]
I've added a page in the wiki about bills:

https://github.com/JC5/firefly-iii/wiki/Bills

You're welcome to start translating! I'll add 'pl' to the current translations, which will contain the English text. You're welcome to add the translations through pull requests (on the develop branch).

**Comment by JC5** [comment]
Released 3.4.11

https://github.com/JC5/firefly-iii/releases/tag/3.4.11
