### ISSUE TITLE
PiggyBag doesn't update.

### ISSUE THREAD

**Issue by vDorst** [JC5/firefly-iii#102]
Version v3.4.10

* Create a PiggyBag x value
* Say is 100% filled.
* Added some transaction from the past.

The chart only shows the initial x value.

**Comment by JC5** [comment]
I'm not sure what you mean.

* I've created a piggy bank called "test" for 1000.
* Chart is blank
* I add 100 from the account the piggy bank is associated to.
* Chart gets one entry (one datapoint) and + 100
* I do it again.
* Same thing.

In the database, I've edited one of the two events to be a day earlier. Now I get a nice line chart.

* I make a transaction (transfer) TO the account the piggy bank is associated to.
* The amount gets added to the piggy bank just fine.
* Same when I remove money

![screen shot 2015-08-08 at 15 33 54](https://cloud.githubusercontent.com/assets/5889984/9150613/f01b96ec-3de2-11e5-9a23-970ab15ace63.png)

**Comment by vDorst** [comment]
```I make a transaction (transfer) TO the account the piggy bank is associated to.```

Ah this is my problem.
transaction is not from the associated account.

It is working is I do it right.
