### ISSUE TITLE
Implement general "account number" instead / in addition to iban

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#107]
IBAN is too local. Add "account number".

**Comment by webenhanced** [comment]
+1 for this.

**Comment by JC5** [comment]
This field should be:

- In account_meta;
- Free format;
- Visible in the edit/create screen;

**Comment by JC5** [comment]
- Unique over all the users accounts. Needs a validator
- Included in the CSV import (mapper, converter, the works).
- Included in the exporter

I'll build those.
