### ISSUE TITLE
nginx: 404 Not Found

### ISSUE THREAD

**Issue by dofl** [JC5/firefly-iii#108]
I've installed according to the installation guide on a fresh Ubuntu 14.04.03. MySql is running, PHP 5.6 and Nginx as well. All the required modules are installed.

When I go to the URL http://mydomain.com/public, I'm redirected to http://mydomain.com/public/auth/login and nginx displays a 404 Not Found.

I'm using the default nginx profile for the website:
server {
        listen 80;

        root /var/www/firefly;
        index index.html index.htm index.php;

        server_name mydomain.com;

        location / {
                try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
        }
}

I'm sure it's something stupid, but I have no clue. 
There is no additional error information in the php5-fpm.log or the nginx error log.
My phpinfo() can be viewed here: https://www.dropbox.com/s/338v3mjuf1nqwue/phpinfo-overseer.html?dl=0

**Comment by JC5** [comment]
My nginx file looks like this. Might this help?

```
server {
	listen 80;
	listen [::]:80;
        # pass the PHP scripts to FastCGI server listening on the php-fpm socket
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }

	root /sites/firefly-iii/public;

	# Add index.php to the list if you are using PHP
    client_max_body_size 300M;
	index index.html index.htm index.php;

	server_name firefly.app;

	location / {
try_files $uri $uri/ /index.php?$query_string;
autoindex on;
sendfile off;
	}

}
```
