### ISSUE TITLE
Category per month not showing

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#109]
I don't know exactly what causes it; but some categories do not show the monthly totals in the diagram.

**Comment by JC5** [comment]
I'm not sure which diagram you mean. Could you give the URL of the page it is on?

**Comment by xzaz** [comment]
categories/show/9 for example. Some months are not showing up while there are transactions within that month.

**Comment by JC5** [comment]
Alright the charts are a bit buggy, but this has also to do with the fact that the category overview is kind of pointless, in its current form. I'm going to think about, and build a new one.

**Comment by xzaz** [comment]
That's fine.

**Comment by JC5** [comment]
Let me know what you think! I'm going to close the issue.

**Comment by xzaz** [comment]
I think this is much better :+1:
