### ISSUE TITLE
Loginpage portrait mode

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#114]
The login page does not auto-adjust itself to portrait mode.

**Comment by JC5** [comment]
I'm not sure what you mean. On your phone?

**Comment by xzaz** [comment]
Yes, on the phone.

**Comment by JC5** [comment]
Ah yes. The box has some weird CSS that pushes it outside of the view when shown in portrait. I'll get on it.

**Comment by JC5** [comment]
Fixed.
