### ISSUE TITLE
Duplicate menu entry (Create stuff menu)

### ISSUE THREAD

**Issue by PeterFour** [JC5/firefly-iii#116]
The left menu contains the Create Revenue Account items twice, is it a known issue ?

**Comment by RonaldvanMeer** [comment]
I've created a pull requests earlier. Fixing this issue.
Op 12 nov. 2015 11:02 schreef "Peter" <notifications@github.com>:

**Comment by PeterFour** [comment]
Oh I must have install the app right before the pull then, sorry :)

**Comment by RonaldvanMeer** [comment]
No problem.
It has been fixed in the development branch as i can see it.
see #113
