### ISSUE TITLE
How to change default currency

### ISSUE THREAD

**Issue by dev-s** [JC5/firefly-iii#121]
Hi

when any user login I want to set a new currency as default. I dont want all users to go and set this currency. How to change the default currency from Euro to any other currency for all users?

**Comment by JC5** [comment]
I've pushed a fix that will allow you to set a default currency (for all users) in the ``.env`` file. Change it to "USD" instead of "EUR" and you should be fine.

``.env.example`` shows you an example (with EUR of course ;)).
