### ISSUE TITLE
Extension of saving account and transaction

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#122]
Just a extension (low prio) for extending transactions from and to the saving accounts:
* interest date, when is the interest counting for this transaction
* book date, when the transaction is booked for the account
* date processing, when is the transaction processed

Extension saving account:
* interest per year / month

The problem is, when I transfer money from one account to another account the money isn't directly available on the other (savings)account. 

It would be nice if we can make a difference between these dates and get a list of transactions that are still processing; i.e; the date date processing is in the future.

If you got the interest on a saving account you can calculate a approximate build interest.

**Comment by JC5** [comment]
That's a very good idea, and it's something that I need myself as well.

The interest calculation is going to be difficult, but it's worth to take a look at. Especially when interest rates change monthly, the calculations need a lot of code.

But the dates, yes, I'll look into it!

- "date": original date from FF, will be the date when the transaction is processed (removed from source account). In FF, transactions are instantly processed at the moment.
- "interest_date". Will be new and optional. Defaults to "date" when unused.
- "book_date". When the receiving account gets the money. Will be "date" when unused.

Something like that?

**Comment by xzaz** [comment]
I agree, we have to keep it simple though. So keeping the 'dates' default on today will do the trick. So *interest_date* and *book_date* will be nullable. 

It will be 'big' update because you need to check for all the reports the book_date. Hence, that is the date when the money is really on the account.

**Comment by JC5** [comment]
Implemented. Next step will be to actually use the dates.
