### ISSUE TITLE
How to swap , and . in amount?

### ISSUE THREAD

**Issue by dev-s** [JC5/firefly-iii#123]
Lets' say we have 5000 salary revenue. The amount shows is 5.000,00 

How to change this to 5,000.00?

**Comment by JC5** [comment]
At the moment, you can't. The number formatting is hard coded.

However, I've pushed a fix. This will be released in the next version. Firefly will then use the correct setting, depending on your language.

**Comment by dev-s** [comment]
Thanks...could you let us know which file it is hard coded?
