### ISSUE TITLE
add brazilian portuguese language

### ISSUE THREAD

**Issue by tonicospinelli** [JC5/firefly-iii#125]
I'm working on it! PR coming as soon as possible :wink:

**Comment by JC5** [comment]
Sounds good, I'll add it for sure!

**Comment by tonicospinelli** [comment]
@JC5 do you know transifex? Is a translation platform, is very simple to use and is possible to add translators and reviewers for any language. It is compatible with php array, but not short array syntax.

https://www.transifex.com/tonicospinelli/firefly-iii/

**Comment by PeterFour** [comment]
I can also help you for a French translation if you're interested

**Comment by tonicospinelli** [comment]
@PeterFour you're welcome!! :smile:

**Comment by tonicospinelli** [comment]
@PeterFour I moved the project to https://www.transifex.com/firefly-iii/firefly-iii/

**Comment by tonicospinelli** [comment]
@JC5 @PeterFour  I was read about live integration with Transifex, and it would be so interesting to do.
http://docs.transifex.com/integrations/overview/

**Comment by JC5** [comment]
Wow guys, this is pretty amazing!

I've submitted myself to the team. Let me know how I can help!

**Comment by tonicospinelli** [comment]
@JC5 I have the same feeling about it, but we can use Transifex Open Source without live.

About translatable content, my ideia ever been about resources from `resources/lang/en/*.php` files. (the system files)

I think Transifex platform is good for final users, they can help in quick way the FireFly-III Project to get more languages. So, we get a User Interface to translate system data and further get more control about translations.

For example, we can download resources from transifex resources every minor release. I know that is a ant job, but is more powerful than we have now :wink:

**Comment by PeterFour** [comment]
Laravel might have a i18n system built in, no ?

On Thu, 3 Dec 2015 at 12:20 Antonio Spinelli <notifications@github.com>
wrote:

> @JC5 <https://github.com/JC5> I have the same feeling about it, but we
> can use Transifex Open Source without live.
>
> About translatable content, my ideia ever been about resources from
> resources/lang/en/*.php files. (the system files)
>
> I think Transifex platform is good for final users, they can help in quick
> way the FireFly-III Project to get more languages. So, we get a User
> Interface to translate system data and further get more control about
> translations.
>
> For example, we can download resources from transifex resources every
> minor release. I know that is a ant job, but is more powerful than we have
> now [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JC5/firefly-iii/issues/125#issuecomment-161618695>.
>
-- 

Pierre Wroblewski

**Comment by JC5** [comment]
This seems doable.

To integrate the Transifex translations into Firefly, I'll have to move the Transifex project to my own organization, effectively taking it away from @tonicospinelli. If I can have your permission, I'll move forward.

**Comment by PeterFour** [comment]
Using a proper i18n system will probably use different file form, like XLIFF.
But easier to handle and translate

On Fri, 4 Dec 2015 at 06:00 James Cole <notifications@github.com> wrote:

> This seems doable.
>
> To integrate the Transifex translations into Firefly, I'll have to move
> the Transifex project to my own organization, effectively taking it away
> from @tonicospinelli <https://github.com/tonicospinelli>. If I can have
> your permission, I'll move forward.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JC5/firefly-iii/issues/125#issuecomment-161885099>.
>
-- 

Pierre Wroblewski

**Comment by tonicospinelli** [comment]
@JC5 yes, of course, bring it on, I added you as admin of transifex project

@PeterFour yes, now is possible to define what file type that will be used, maybe change to XLIFF or keeping php array?

**Comment by PeterFour** [comment]
Well if PHP array is not causing any problem in transifex might as well
keep it that way for now

On Mon, 7 Dec 2015 at 23:01 Antonio Spinelli <notifications@github.com>
wrote:

> @JC5 <https://github.com/JC5> yes, of course, bring it on, I added you as
> admin of transifex project
>
> @PeterFour <https://github.com/PeterFour> yes, now is possible to define
> what file type that will be used, maybe change to XLIFF or keeping php
> array?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JC5/firefly-iii/issues/125#issuecomment-162699313>.
>
-- 

Pierre Wroblewski

**Comment by tonicospinelli** [comment]
I have one point about PHP array, not is possible using multi-dimensional array such as:
```php
   // validation.php
"between"                 => [
    "numeric" => "The :attribute must be between :min and :max.",
    "file"    => "The :attribute must be between :min and :max kilobytes.",
    "string"  => "The :attribute must be between :min and :max characters.",
    "array"   => "The :attribute must have between :min and :max items.",
],
```

**Comment by JC5** [comment]
It's not up to me, those sentences are used by Laravel internally as "between.numeric". I have to test the following:

```php
// validation.php
"between"                 => [
    "numeric" => "The :attribute must be between :min and :max.",
],
```

Equals:

```php
// validation.php
"between.numeric" => "The :attribute must be between :min and :max.",
// etc....
```

I am not yet sure. Will report back.

**Comment by JC5** [comment]
After some consideration, and mailing to and from Transifex, I've decided to move the entire thing to [Crowdin](https://crowdin.com/project/firefly-iii).

Contrary to Transifex, they allow me to upload and download the translation files in their original formatting, without losing comments or formatting. All translations so far have been auto-recognized. Tomorrow, I will close the project at Transifex.

I would really appreciate it if you could make the move with me to Crowdin!

**Comment by tonicospinelli** [comment]
@JC5 OMG!!! Crowdin is awesome tool too!! I really forgot it!!!

**Comment by PeterFour** [comment]
Got myself back on Crowdin then :)
