### ISSUE TITLE
Make reporting year configurable

### ISSUE THREAD

**Issue by webenhanced** [JC5/firefly-iii#131]
Hi James, I congratulate you on this nice piece of software you are sharing. Thanks.

I am wanting to add features to it and would like to know some stuff before I get going:-
- Should I always work from the 'master' branch? I ask this because I see some nice localization of number formats happening in the 'develop' branch but it is 5 commits behind 'master'.
- The first feature I want to add is making the reporting year start and end dates configurable; either from 'config' or preferences. In many countries (including my home Australia) we report for tax purposes from dates other than the calendar year. Here it runs from 1st July to 30th June.

How is the best way to communicate with you while this development is happening?

Thanks, Graham

**Comment by JC5** [comment]
Hi!

First of all, thanks! I appreciate the compliment.

Always work in the "develop" branch. You can read more about the [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/), or Google it. The best you can do is checkout the develop branch, get a sense of what you need to do and then, use Github to create a "pull request". In the pull request, you'll write all the changes you wish to implement.

As far as I am concerned, the changes you would like to implement can be as big or as small as you'd like, although I'd prefer small incremental changes, possibly in multiple pull requests.

If you want to change the reporting year, you can already select a custom range on the reports page. ``2014-07-01 - 2015-06-30``. This should work, at least partially.

As you can see on the report page, there's a whole bunch of "pre-set" ranges already. It should be fairly easy to add more ranges to that list.

To implement your idea, I would suggest something like this:

* A preference (true/false) called something like "I want to setup a custom fiscal year" on the preferences page.
* Two dates, start and end. "1st of July" and "30th of June" for example. No year selection. Or maybe this date is different every year? Who knows! Let me know. It should be put on the preferences page.
* Once this has been configured by the user, and turned on, the report page (index) could show something like this:

```
2014 2014 (fiscal year)
January 2014  February 2014 [...]
2015 2015 (fiscal year)
January 2015  February 2015  [...]
```

It would look better in HTML of course. Or maybe there's another smart way. Open an issue, write a pull request, and just add it. I would suggest building it in this order:

* Create a true/false preference on the preferences page. Make sure it can be localized and add English translations. The other ones, you can ignore them for now. Put this in one pull request.
* Create the date preferences. Put this in another pull request.
* Edit the report-index so it will respond to the preferences.

For all other stuff such as localization, bug fixes, translations and anything else, create a pull request, open an issue or do both. 

Thanks in advance for your help! If you want to communicate with me outside of Github, you can always drop me a line at thegrumpydictator@gmail.com

James

**Comment by webenhanced** [comment]
Thanks for the workflow and collaboration info. I can certainly work with that.

I am an old timer used to the centralized workflow approach and do not have a lot of experience on github, thus the tendency to begin on the master branch. But i like the gitflow workflow and will follow that no problems.

I'll start as you have suggested, 
- will start with the develop branch,
- create a feature branch from that locally,
- get a working preferences going,
- push that branch back to github,
- then submit the required pull requests for your consideration.

Does that sound right to you?

Cheers, Graham

**Comment by JC5** [comment]
Sounds good!

Feel free to use Firefly as a training ground; I don't consider myself to be strict, and I'll promise not to be annoyed too much. ;-). Remember the "develop" branch is used by very few people so even if you break stuff, and neither of us spots it, it's still a long way from being published as an actual upgrade.

Cheers,

James

**Comment by webenhanced** [comment]
It has taken a while (bit of a learning curve), but I have a working version and have just made a pull request #149.

It has been implemented against an reasonably up-to-date develop branch.

Let me know what you think?

**Comment by JC5** [comment]
This is wonderfully well made! I thought had some comments, but nothing sticks. At least nothing worthwhile. I'm nitpicking, and those do not count. 

Thanks!

**Comment by webenhanced** [comment]
Glad you like it.
I'll add a new quick link report for current fiscal year all accounts (if OK with you), submit pull request, and then close this issue off once its accepted.

**Comment by JC5** [comment]
Sounds good!
