### ISSUE TITLE
Laravel not updated in new release

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#139]
When executing ` php artisan migrate` for a update I get:

```
[InvalidArgumentException]
  Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Str': Class
   TwigBridge\Extension\Laravel\Str does not exist
```

**Comment by JC5** [comment]
Try the following:

``git pull``
``rm -rf vendor/``
``composer install``

Should reinstall all packages. The problem stems from the fact that the updated Twig uses "Str" but the old one uses "String". I can't use the new one until you've upgraded but the old one breaks when using PHP7.

**Comment by xzaz** [comment]
Thanks
