### ISSUE TITLE
Call to undefined function FireflyIII\Support\money_format()

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#140]
Hi,
I did a git clone per the installation guide, and managed to install firefly.
However after registering a user, I get some errors:

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function FireflyIII\Support\money_format()' in [..]\firefly\app\Support\Amount.php:63
Stack trace:
#0 {main}

**Comment by zjean** [comment]
Ah, it looks like that the money_format function is not supported on Windows per http://stackoverflow.com/questions/6369887/alternative-to-money-format-function-in-php-on-windows-platform

**Comment by RonaldvanMeer** [comment]
So it is a bug on a Windows platform. I believe a requirement is to install intl extension. Pehaps the intl function is not used but the platform (OS) function is.
If so this needs to be fixed.

**Comment by JC5** [comment]
I want to replace the money_format function one of these days.

With the way Firefly has grown, money formatting went from "the way I liked it" to "the way international money formatting actually works". So the code is a bit behind.
