### ISSUE TITLE
Feature: split transactions

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#142]
Let's finally make this happen.

Basic idea: transaction journals stay the same. Transactions will be added to the journal in groups of two. Let's break down a 2000,- salary (first implementation will support only deposits).

From Boss to Me, 1500,-, in category Salary.
From Boss to Me, 250,-, in category Car
From Boss to Me, 250,-, in category Bonus

Could even go to different accounts or come from different accounts. All three items listed above will need 6 transactions in total.

**Comment by JC5** [comment]
Start with deposits.

When creating a new deposit, the option appears to split the deposit. Table will show up, like so.

![Idea](https://i.nder.be/gk6pm5v6)



The total amount should equal the original amount (otherwise split will result in bigger transaction journal). Rules can apply to these transactions as well. Transactions need a field "order".

**Comment by JC5** [comment]
This will impact just about everything in Firefly III.

**Comment by xzaz** [comment]
Is this something they do in the finance world? Or is this a YNAB thing?

**Comment by JC5** [comment]
It's a choice, you can go either way.

Firefly stores each financial transaction in "journals". Each journal
contains two "transactions". One takes money (-250 from your bank account)
and the other one puts it into another account (+250 for Amazon.com).

You can verify this by counting. There are always twice as many
transactions as there are transaction journals in your database.

Not splitting transactions (or as FF calls them, "transaction journals")
means that Firefly stays true to what a transaction is, which is singular.
Money moves from A to B, end of story. Nothing more.

However, often a transaction tells a story. Just take grocery receipts for
example. It's one transaction sure, but it consists of many parts. And when
you buy aspirin and bread at the same time, you might want to split the
transaction over two budgets, medication and groceries. A single
transaction would make you lose information.

Likewise, your salary may have multiple components. Your base salary may be
1200. Minus 200 for taxes. Plus 100 bonus. Etc. All that information is
lost when you only support singular, unsplitted transactions, like Firefly
does.

YNAB allows you to retain that information by creating complex transactions
that end up with the same amount but offer a whole lot more information.
Also, it gives you more fine grained control over your finances because the
"simple" transactions your bank shows you are translated back into their
complex contents. Which of course can be very useful.

**Comment by JC5** [comment]
TODO for split journal support:

- Support split journals when exporting. The export routine will currently not export more than 1 source or destination account. See FireflyIII\Export\Entry\Entry.php:68
- Connect a journal to a piggy bank might incorrectly calculate amounts because multiple source accounts may exist. See FireflyIII\Handlers\Events\ConnectJournalToPiggyBank:47
- Piggy banks are not yet supported. May require database changes.
- Advance payment tags may not properly recognize a split journal. See FireflyIII\Repositories\Tag\TagRepository:232

**Comment by JC5** [comment]
rules. The following triggers do not support split journals
* amount is more than
* from account contains
* from account starts with
* from account ends
* from account is
* to account contains
* to account starts with
* to account ends
* to account is
