### ISSUE TITLE
The multi-year "no budget" selection does not seem to work.

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#151]
Investigate and fix.

**Comment by roberthorlings** [comment]
The no budget page currently uses the `viewRange` preference to decide on which transactions to show. However, it seems more intuitive to use the range as specified in the top menu bar in the UI (stored in session `start` and `end`). This is also done in other pages, e.g. `/categories/list/noCategory`

Would that solve the problem?

**Comment by JC5** [comment]
No, but good catch. I have updated the code.

The issue applies to this page: http://your-firefly.site/reports/report/default/20150101/currentMonthEnd/1,2,3,4,5

Transactions not belonging to a budget are not represented in that budget chart. But should. See FireflyIII\Http\Controllers\Chart\BudgetController::multiYear.
