### ISSUE TITLE
.env missing

### ISSUE THREAD

**Issue by RC5** [JC5/firefly-iii#158]
I followed the installation tutorial for 
`git clone https://github.com/JC5/firefly-iii.git --depth 1`

Could not find .env -file to complete next step

`Git pull` 
did not resolve the file to appear

![firefly-iii root env file missing](https://cloud.githubusercontent.com/assets/16993607/12705439/53016a2e-c872-11e5-8c1c-edc954dda457.PNG)

**Comment by webenhanced** [comment]
Copy .env.example to .env and you should be good to go. (cp -a .env.example .env)
When using ls to see directory listing use ls -a to see the dot (hidden on linux) files.

**Comment by JC5** [comment]
Good catch! Indeed, you have to copy ``.env.example`` to ``.env``. I will update the wiki so this is mentioned.

**Comment by RC5** [comment]
Thanks guys, i found the file
