### ISSUE TITLE
CSS issue on landing page out of the box

### ISSUE THREAD

**Issue by RC5** [JC5/firefly-iii#161]
I have installed the package on Lubuntu 15 with required server modules. 
However the dashboard landing page does not display any css format (out of the box).

Attached index/html (including css)
[index.php.txt](https://github.com/JC5/firefly-iii/files/112361/index.php.txt)

Attached chown access rights of public folder
[list access rights public.txt](https://github.com/JC5/firefly-iii/files/112374/list.access.rights.public.txt)

Attached error.log (php/apache)
[error.log.txt](https://github.com/JC5/firefly-iii/files/112383/error.log.txt)

Any ideas what the errors in error.log-file might relate to and how this can be resolved?

> Please note, i did load index.php prematurely and discovered that the mcrypt-module was not installed. The landing page did display a css-page with warning "Whoops, looks like we have a problem." (mcrypt has been resolved)

> Please note also i have setup a vhost configuration. I'm currently double checking my <Directory> settings and htaccess file for incorrect values

**Comment by JC5** [comment]
In index.php.txt line 12: <base href="http://lubuntu-vm/index.php/">

Is apache setup with mod rewrite?

**Comment by RC5** [comment]
There is a .htaccess file in the public root with rewrite
```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

**Comment by JC5** [comment]
Ok, that looks good. But is mod rewrite enabled? You can check by trying to visit http://lubuntu-vm/password/reset

**Comment by RC5** [comment]
Results in 

> Not Found
> 
> The requested URL /password/reset was not found on this server.
> 
> Apache/2.4.12 (Ubuntu) Server at lubuntu-vm Port 80

**Comment by JC5** [comment]
That means that the mod rewrite is not enabled. Try this command:

``sudo a2enmod rewrite; sudo apache2 reload``

**Comment by JC5** [comment]
If that does not work, open your apache configuration, and find this part (or something similar):

```
<Directory /var/www/firefly-iii/public/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
```

Then change ``AllowOverride None`` to ``AllowOverride All``

**Comment by RC5** [comment]
Yeh, i will try the command you suggested.
The virtual host config file on my virtual machine has rewrites too. 
Looks like a server issue. I will check and look into it.

**Comment by RC5** [comment]
Yes, it was indeed the apache2.conf file but i was using the wrong apache restart command.

/etc/init.d/apache2 restart (worked)
service apache reload (did not work)

:+1:
