### ISSUE TITLE
Reconcile accounts

### ISSUE THREAD

**Issue by webenhanced** [JC5/firefly-iii#164]
Are there any plans to implement the ability to reconcile asset accounts from the bank statements? This would be a good feature IMHO.

**Comment by JC5** [comment]
Not yet, but it should not be difficult. What we need is the ability to recognize individual lines from imported bank statements. One way is to simply save the entire line into the database. 

It might be a good idea to add something like "transaction_journal_meta". This table could hold (like account_meta) all kinds of meta-information. Good idea!
