### ISSUE TITLE
Fatal error when rescanning transactions on a bill.

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#167]
I get an error (on the master branch) when I click on the Rescan old transactions button on a bill.
The bill has one transactio associated with it. 

FatalErrorException in BillRepository.php line 178:
Call to a member function pluck() on array

[https://github.com/JC5/firefly-iii/blob/master/app/Repositories/Bill/BillRepository.php#L178](Code)

**Comment by JC5** [comment]
This has been fixed in develop!
