### ISSUE TITLE
Errors on composer.lock

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#179]
Hi,
when I do clean checkout of the develop branch, and run a composer install, I get this error:

`[RuntimeException]
  The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.`

When I run composer install --no-dev, i see
`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.`

I try to add the package pragmarx/google2fa (to implement 2fa) by running
`composer require pragmarx/google2fa`
but a new composer install does not download and add the package.
Can you fix the lock file problem?

**Comment by JC5** [comment]
I've pushed a new composer.lock. If it still will not update, run

``rm -rf composer.lock vendor/``
``composer update --no-scripts``
``composer update``

This will bring composer.lock out of sync, so don't commit it, but it will allow you to run

``composer require pragmarx/google2fa``

**Comment by JC5** [comment]
Wait no, the current composer file should be up to date. Just do the above thing.

**Comment by zjean** [comment]
Ah, that works. Thanks!
