### ISSUE TITLE
Issue with deleting and recreating account

### ISSUE THREAD

**Issue by AxisNL** [JC5/firefly-iii#184]
I messed up my imports (of course) and just wanted to see how firefly worked. Now that I got the hang of it, I want to start fresh. I deleted my account from the menu and then I go to the login screen.

I would expect my account to be gone from the DB. Now I cannot log in anymore (duh, of course!), but upon registering a new account, it says 'The email has already been taken', which I did not expect. 

I'm going to drop an recreate the DB now.

**Comment by JC5** [comment]
The code responsible for this routine is [right here](https://github.com/JC5/firefly-iii/blob/master/app/Http/Controllers/ProfileController.php#L105).

I did this so sneaky hobbitses would not recreate their account on the demo site right after I emailed them they were through their trial time.
