### ISSUE TITLE
Export page

### ISSUE THREAD

**Issue by AxisNL** [JC5/firefly-iii#195]
I would love to see some kind of export page, where I can export all my transactions and accounts (to CSV, xml, whatever), or perhaps show a big table with all transactions per account (including the actual balance of the account after the specific transaction). 

In my case, I made a mistake somewhere during my imports and changing withdrawals to transfers (which means removing the transaction and re-adding it again as tranfer). Now, it seems my bank balances do not match the balances according to my statements, so I messed up somewhere and I am in a non-consistent state. I want to view all my existing transactions and match them to my paper bank reports. If I look at a paper bank statement, the end-balance will have to match the actual balance in the report of course.

I tried looking in the database, but I see all kinds of hashed stuff, so I can't generate the report I need. But I think this new functionality serves a more general purpose to more people than just me.

**Comment by JC5** [comment]
The first one will be available in Firefly 3.8.0. In this new version, an export tool has been added that looks like this:

![screen shot 2016-02-23 at 16 06 02](https://cloud.githubusercontent.com/assets/5889984/13255670/64de0c52-da47-11e5-89d9-fddef3a0895a.png)

There is a view to show all of your transactions for a specific account. Go to Accounts, Asset accounts, and pick one. A list of transactions should present itself. However, this list does not include the balance before or after the transaction took place. You may click each individual transaction, but this is quite time consuming.

I think I could build such a report or extend this particular view.

**Comment by AxisNL** [comment]
The export tool looks cool, looking forward to it. 

Currently I can see the list of transactions for an asset account, but it's paged, and I cannot get everything on one page I guess (I have 17 pages now). I'd really like to see the 'new balance' on the transaction overview page as well, but that's up to you to decide.

**Comment by JC5** [comment]
Will open a new issue for the report thing.
