### ISSUE TITLE
Firefly-iii Docker Container

### ISSUE THREAD

**Issue by willemdh** [JC5/firefly-iii#203]
Anyone got this working on Docker?

**Comment by JC5** [comment]
I'll give it a try myself this Sunday!

**Comment by willemdh** [comment]
Well I'm renting a Linode server with several application on it. I fear installing Firefly-iii will break some stuff due to PHP requirements etc. Being able to run it in a Docker container would solve this issue. :)

**Comment by JC5** [comment]
I haven't had the time to try it. I hope to get some time this weekend to play around with it.

**Comment by JC5** [comment]
Alright I'm pretty sure I _could_ get Firefly III to run in a docker container. Question is if I _should_. It's not stateless and has many dependencies and at least three processes. That's not really light weight.

**Comment by willemdh** [comment]
@JC5 It was just an idea to prevent requirement issues. I know that I'm not able to install this on my Linode server, as I can't install PHP 7 for example. If it worked on Docker, the requirements wouldn't matter. But of course it's all up to you.. :)
