### ISSUE TITLE
Specific bill date

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#206]
Nowhere in Firefly III is the specific day of a bill used. Ie. "expected March 12th". Nobody is expecting it on that day, except perhaps maybe the user. It should be possible to use this information in a more useful way. If the date is not exact or relevant the user should be indicate this as such (for example when the user pays the bill himself and may wait a few days before doing so) with an option or a field. Or maybe reverse, only when the bill is expected a specific date the system should respond.

Regardless of that option, Firefly does not respond to an exact "expected at"-date in any way. So either Firefly should respond to such a date (with a reminder or an alert) or it should not ask for such a specific date in the first place.

**Comment by mrdeadlocked** [comment]
This would be a very useful enhancement.
