### ISSUE TITLE
ING csv import 

### ISSUE THREAD

**Issue by Doeners** [JC5/firefly-iii#210]
Hi, when trying to import a ing csv statements al the transactions are add to income. they have a column "Af/Bij" which indicate if its a expense or an income.

For description of the csv look at:
https://www.ing.nl/media/ING_csv_mingz_aug14_24_juli_tcm162-45557.pdf

**Comment by JC5** [comment]
Pushed an update. You'll have to switch to the develop branch (if you know how), or wait for the next version :).

**Comment by Doeners** [comment]
Thanks i just updated the 3 files you changed :)
:+1:

**Comment by JC5** [comment]
Good! You're missing out on translations though ;).

I'm going to close the issue. If you have questions or problems, let me know!
