### ISSUE TITLE
Finishing 2 factor authentication

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#219]
Just a quick reminder for me to finish things up:
- implement custom guard (please give your advice on this)
- implement verification of code after login
- nice to have: implement backup codes

**Comment by JC5** [comment]
I will, but after the release of 3.8.0, which is due pretty soon. I had some other things going on, and I'll get back to you.

**Comment by JC5** [comment]
Alright, I've tried the custom guard and it's pretty much a dead end. You were spot on with the original implementation, which was an extra middleware thing.

I've built something already but if you want to finish this, I won't commit it. Here's what I did, globally. 

* Create a new middleware to check for two-factor. Add it to the relevant groups.
* Create a middleware group that doesn't check for 2fa.
* Create a input code view thing for users to input the code.

You can use the session as long as you hook on the logout event to remove the "is-authed-with-two-factor" thing.

Incidentally, your preferences screen shows and sends the user's secret to them. That seemed like a bad idea so in 3.8.0 i've removed this. Get the latest code once it's released.

**Comment by zjean** [comment]
Hi thanks for your reply.
Please commit and push what you have built, maybe I can add some extra features if needed.
