### ISSUE TITLE
.env.example missing

### ISSUE THREAD

**Issue by sschimmel** [JC5/firefly-iii#220]
I just cloned the repository with the instructions in your documentation and noticed that the .env.example file is missing. Please add the file so it's possible to configure firefly.

**Comment by JC5** [comment]
It's right there. Did you accidentally type "``env.example``", or are you not in the ``firefly-iii`` directory perhaps?

https://github.com/JC5/firefly-iii/blob/master/.env.example
https://github.com/JC5/firefly-iii/blob/develop/.env.example

Check if the file is not hidden, by listing the content of your firefly-iii directory using ``ls -lah``

**Comment by sschimmel** [comment]
Ok, weird. I see it's in the master branch and hasn't changed since two months. Nevermind :-) Got it working.
