### ISSUE TITLE
It seems the two factor authentication code is forgotten constantly

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#228]
I am not sure if it is because my personal installation is off somehow, or because it is a bug. The code seems straight forward enough:

``Session::put('is2fa',true);``

``Session::get('is2fa',false) === true``

But something is off regardless, I get to have to enter a code way too often.

**Comment by JC5** [comment]
This happens when the cache is flushed using HomeController::flush. This routine clears all session data as well, which is where this entry is kept.

**Comment by jacopo-j** [comment]
Hello. I've been using the latest release of Firefly without any problem for some weeks, but now I do have this problem. 2FA code is asked almost every time I visit Firefly, even at a few hours distance. Is there any workaround?

**Comment by JC5** [comment]
Yes this is very annoying. It’s on my list to improve
