### ISSUE TITLE
Unable to: "Execute for existing transactions" button

### ISSUE THREAD

**Issue by uffer** [JC5/firefly-iii#230]
Hi JC5,

During some test I'am unable to use the: Execute for existing transactions button.

A quick tail from the log: tail -f laravel-2016-03-28.log

`#71 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /var/www/html/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#75 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /var/www/html/firefly-iii/bootstrap/cache/compiled.php(9787): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#77 /var/www/html/firefly-iii/bootstrap/cache/compiled.php(2340): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#78 /var/www/html/firefly-iii/bootstrap/cache/compiled.php(2324): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#79 /var/www/html/firefly-iii/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#80 {main}`

And a email with this error:

` Firefly III ran into an error: Undefined property: FireflyIII\Repositories\Account\AccountRepository::$user

The error was of type "ErrorException".

The error occured on/at: Mon, 28 Mar 2016 11:55:31 +0000.

This error occured in file /var/www/html/firefly-iii/app/Repositories/Account/AccountRepository.php on line 85 with code 0.

The error was encountered by user #1, firefly@domain.com.

The IP address related to this error is: *.*.*.*

The full stacktrace is below. If you think this is a bug in Firefly III, you can forward this message to thegrumpydictator@gmail.com. This can help fix the bug you just encountered.

If you prefer, you can also open a new issue on Github.

The full stacktrace is below:`

The webpage is showing:
`FireflyIII
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Undefined property: FireflyIII\Repositories\Account\AccountRepository::$user`

Is this a problem on the serverside I can fix?

**Comment by JC5** [comment]
Hi! It's a problem in 3.8.0. I will release 3.8.1 tomorrow, if all goes
well. My apologies for the inconvenience.

**Comment by uffer** [comment]
Ok, cool! 

Will test the function after the update.

For the rest it is a really cool application!!

Uffer

**Comment by JC5** [comment]
Thanks! I'm closing this, it'll be fixed soon.
