### ISSUE TITLE
Accounts doesn't save everything

### ISSUE THREAD

**Issue by svenpool** [JC5/firefly-iii#233]
Hi, 

I created an Account and filled in everything, even the opening balance date and opening balance, when I wanted to edit the Account I saw that 'Account Number' is missing. When I try to add this, it isn't saved. Furthermore if I edit an existing value like the Opening Date then this information is saved. 

Secondly I created a second Account, but left open the opening balance date and opening balance. I would like to adjust that now, but whenever I try to fill in this information it's not being saved. P.S. Account number was filled in and is also missing when I edit the account.

It shows no errors, not in the storage/logs or the Apache logs.

**Comment by JC5** [comment]
Hey,

I can reproduce both bugs, but I am not sure why the data is not stored. A fix will be forthcoming in 3.8.2, which I will probably release this weekend. 

When I've found the cause, I'll let you know!

**Comment by svenpool** [comment]
Great! Furthmore the application looks good :) Thanks for the support.

**Comment by JC5** [comment]
The bug has been fixed!
