### ISSUE TITLE
Merge Converter\Amount and Converter\AmountComma

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#235]
These two classes should be one:

* The amount can be 1000000.00 or 10000,0000 (should not matter).
* Amount could also be 123.456,11 or 123,456.00 (should also not matter)
* Amount could be 10000 (should also not matter)

One converter to rule them all.

**Comment by roberthorlings** [comment]
I think combining these converters may be difficult, see also the comments in https://github.com/JC5/firefly-iii/pull/146.

For example, what would be the result of parsing 10,000, 10.000, 10000.000 or 10000.00.

**Comment by JC5** [comment]
There's a line to draw somewhere. The current method is far from foolproof.

There are currently just a few currencies that do not divide in 100 cents to the coin. I am not hesitant to drop support for these (there are four of them).

As long as systems place the decimal separator and the thousand separators correctly (a reasonable assumption of other financial systems) it would be easy:

* "x.xx" denotes a value where the decimal separator is a dot. The thousand separator wouldn't even be relevant. Simply cut it all out except for the dot and the digits and you have a valid number. "xx xxx.xx" and "xx,xxx.xx" would give the same results.
* Same applies to "x,xx".
* If the amount ends in "xxx" there's a good chance there is no decimal separator and we only have to look for the thousand separator.

I'm fairly sure that 99.99% of the amounts would be formatted correctly.

**Comment by tonicospinelli** [comment]
probably `NumberFormatter` could help on it, because it use locale to parse and format a number.

[NumberFormatter reference](http://php.net/manual/pt_BR/numberformatter.parse.php)

**Comment by JC5** [comment]
With NumberFormatter you need to know which format the number has already. The current new number formatter is not half bad.
