### ISSUE TITLE
After updating to the latest version, cache contains wrong value types

### ISSUE THREAD

**Issue by nhaarman** [JC5/firefly-iii#237]
I'm not entirely sure which version I _was_ using, but after pulling master to commit a6936cbd0299e0a153c5da17acdb61d07d1379e4 (release/3.8.2), the application crashes due to the following error:

```
Type error: Return value of FireflyIII\Support\Steam::balance() must be of the type string, float returned

This error occured in file ~/Firefly/app/Support/Steam.php on line 38 with code 0.

Stack trace

#0 ~/Firefly/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): FireflyIII\Support\Steam->balance(Object(FireflyIII\Models\Account), Object(Carbon\Carbon))
#1 ~/Firefly/app/Repositories/Account/AccountRepository.php(345): Illuminate\Support\Facades\Facade::__callStatic('balance', Array)
#2 ~/Firefly/vendor/laravel/framework/src/Illuminate/Support/Collection.php(146): FireflyIII\Repositories\Account\AccountRepository->FireflyIII\Repositories\Account\{closure}(Object(FireflyIII\Models\Account), 0)
...
```

Apparently some types have changed, and the cache still contains the old type. Removing line 38 (`return $cache->get();`) fixes things.

**Comment by JC5** [comment]
Good catch! The cache (har har) may indeed contain values that are invalid later.

I'll expand ``composer.json`` to clear the cache once the upgrade / install process has finished.

You can do this manually by either running ``php artisan cache:clear`` in your Firefly III directory, or by browsing to ``/flush``.
