### ISSUE TITLE
Transactions can't be filtered using date filter control

### ISSUE THREAD

**Issue by Amain** [JC5/firefly-iii#240]
Hi,

First of all, awesome software. Finally a tool that does what I need, simple, yet complex enough to provide solutions for the day-to-day financial administration tasks. Easy import of bank transactions, including ING NL is really great. You probably should advertise this software a bit more, I'm sure more people are stuck using other (commercial, paid) financial software with less potential, and much more complexity then needed.

Having said that, I was hoping to filter on transactions using the date range selection control in the top of the screen. However, it seems to only affect the date ranges on reports, so far I've seen. Just starting with the tool.

Not sure if this is a bug, or a feature request. :-) Either way, the date range selector control is not disable, so I was expecting the range to be applied to the screen(transactions) I was on.

Thanks,

Amain

**Comment by JC5** [comment]
Hi!

Thanks for the compliments! I should advertise more indeed :).

The date range filter should filter the following:

- The index page top boxes, charts, and all lists.
- The chart on top of each account page (``/accounts/show/x``) but not the list of transactions.
- Entirety of ``/budgets``, 
- The default click through of each budget.
- The left chart of each ``/categories/show/x`` page.

That's about it really. It should not actually filter the reports, although the default values for the date range may be affected. Other than that, reports are completely independent.

Having said that, it's pretty random what is being filtered and what is not. It depends mainly on which overview I felt like at the time would benefit from being filtered. Most lists are not.

I'll think about how these lists can be improved. I feel that most lists don't really benefit from being filtered, unless you go way back and it would save you from selecting the correct page. The transaction lists (``/transactions/withdrawal`` et al) are more of an archive, and so are the account overviews (``/accounts/show/x``).

Did you have any specific place in mind?

**Comment by Amain** [comment]
Yes. Mainly indeed the /transactions/withdrawal screen (and the account overview screens) where transactions are listed. For example, I'd like to select, review and update only the transactions from last import. Which, because I'm now also importing historical data / transactions, may not be on the first screen, but somewhere in the middle. Which probably takes me quite a few clicks to get to the correct page currently. Or, if I'm not satisfied with this import, I want to be able to select all those transaction, and in one go be able to remove the transactions. Change some rules, budgets, bills and re-import it. 

Another use case I'm thinking of is searching for a specific transaction; for example I know around which date the transaction must have taken place, but want for example to see / verify the amount and / or destination account.

**Comment by JC5** [comment]
The import routine requires a massive overhaul. It's not very flexible, code-wise. I'll write something down.

As for the views, it shouldn't be hard to build. Expect something in the next release.

**Comment by JC5** [comment]
Most of these views are now relative to the date range set. Also accounts. The transactions overview will remain "date-less" for now.
