### ISSUE TITLE
Searching gives 'Whoops'

### ISSUE THREAD

**Issue by Amain** [JC5/firefly-iii#242]
When searching (using search box at top left of screen) I get a 'Whoops'. The logs reveal an SQL issue: 

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'encrypted' in where clause is ambiguous (SQL: select `transaction_journals`.*, `transaction_types`.`type` as `transaction_type_type`, `transaction_currencies`.`code` as `transaction_currency_code`, `destination`.`amount` as `destination_amount`, `destination_account`.`id` as `destination_account_id`, `destination_account`.`name` as `destination_account_name`, `destination_acct_type`.`type` as `destination_account_type`, `source`.`amount` as `source_amount`, `source_account`.`id` as `source_account_id`, `source_account`.`name` as `source_account_name`, `source_acct_type`.`type` as `source_account_type` from `transaction_journals` left join `transaction_types` on `transaction_types`.`id` = `transaction_journals`.`transaction_type_id` left join `transaction_currencies` on `transaction_currencies`.`id` = `transaction_journals`.`transaction_currency_id` left join `transactions` as `destination` on `destination`.`transaction_journal_id` = `transaction_journals`.`id` and `destination`.`amount` > 0 left join `accounts` as `destination_account` on `destination_account`.`id` = `destination`.`account_id` left join `account_types` as `destination_acct_type` on `destination_account`.`account_type_id` = `destination_acct_type`.`id` left join `transactions` as `source` on `source`.`transaction_journal_id` = `transaction_journals`.`id` and `source`.`amount` < 0 left join `accounts` as `source_account` on `source_account`.`id` = `source`.`account_id` left join `account_types` as `source_acct_type` on `source_account`.`account_type_id` = `source_acct_type`.`id` where `transaction_journals`.`user_id` = 1 and `transaction_journals`.`user_id` is not null and `encrypted` = 0 and (`description` LIKE %Search% or `description` LIKE %test% or `description` LIKE %string%) and `transaction_journals`.`deleted_at` is null order by `transaction_journals`.`date` desc, `transaction_journals`.`order` asc, `transaction_journals`.`id` desc) in firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php:673

**Comment by JC5** [comment]
This one will be fixed in the next version. Thanks for mentioning it!

**Comment by Amain** [comment]
Great. Thanks.
