### ISSUE TITLE
Bills paid on dashboard not updated upon filter date range change

### ISSUE THREAD

**Issue by Amain** [JC5/firefly-iii#245]
When altering the date range using the date control in the top of the screen, the 'Bills Paid' from 'What's playing' and the 'Bills' pie chart are not reflecting the actual status. Seems only transactions imported with timestamps after the initial Expected match date of bills are reflected in the graphs. The expenses list though, shows the all the transactions correctly matched to the bills, including those transactions with timestamps before the initial Expected match date. Rescanning old transactions does not seem to change this.

Is this expected behavior?

Reproduction:

* Create bill (initial import date set to 1st of April)
* Import transactions from lets say March, matching configured bills
* Transactions for those bills are matched
* Set date selector to March
* The before mentioned graphs are *not* updated
* Import transaction for April
* Set date selector to April
* The before mentioned graphs are updated

**Comment by Amain** [comment]
Please note that I'm clearing some tables to test my bill and import rules, using SQL. So the integrity of the database might not be guaranteed. So far it seems to work just fine. 

delete from transactions;
delete from transaction_journals;

**Comment by JC5** [comment]
It should show all bills indeed. I'll look into it!

**Comment by JC5** [comment]
Found the source of the bug. Will fix asap.
