### ISSUE TITLE
Collapse and expand boxes on dashboard

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#250]
When collapse (-) and expand (+) the boxes on the dashboard they don't render any more.

**Comment by xzaz** [comment]
For what it's worth; for me the whole functionality can be removed.

**Comment by JC5** [comment]
They're part of the layout. I never found the time to program FF3 to remember the user's preference.

What exactly doesn't render anymore? Is the content gone? Are the mouse-overs broken?

**Comment by xzaz** [comment]
It's the content, mostly the charts that don't render any more.

**Comment by JC5** [comment]
Mmm, that's strange. Did it improve in the most recent version of FF? Which browser are you using? When I close and open the boxes, any box, the content simply reappears and runs fine. I'm using Chrome on a Mac.

**Comment by xzaz** [comment]
I think it changed after the ChartJS update (not the one in 3.8.4). This is the result:
![screenshot_3](https://cloud.githubusercontent.com/assets/2311499/14779614/313e022c-0ad9-11e6-8860-0f32b7f906de.png)

**Comment by JC5** [comment]
I've noticed the same. Firefox only. Seems minimizing the canvas does not agree with them. I'll see what I can do, which may or may not include removing those buttons.

**Comment by JC5** [comment]
I've removed the minimize feature. That should solve it.
