### ISSUE TITLE
Budgets for any period

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#256]
Should be able to create, edit, and manage budgets:

- Daily budgets.
- Weekly budgets
- Monthly budgets
- Quarterly budgets
- Yearly budgets
- Custom range?

It should be possible to create such budgets, edit them and manage them from any point of view.

**Comment by jcalonso** [comment]
@JC5 is it possible to do this now?

**Comment by JC5** [comment]
Yes.

**Comment by geniusupgrader** [comment]
> is it possible to do this now?
> Yes.

Can we open this issue again?
I would favor this and want to reference two other issues for that: #1819 & #1831
