### ISSUE TITLE
PT-BR is done!

### ISSUE THREAD

**Issue by tonicospinelli** [JC5/firefly-iii#257]
@JC5 I translated all stuffs from crowdin 😄 

damn... you bump a new tag 4 days ago... 😒

**Comment by JC5** [comment]
Very nice!

Could you do me a favor and re-open your PR against the _develop_ branch? The master branch is for new releases only.

**Comment by tonicospinelli** [comment]
ouch!! Sorry, my bad!! @JC5 closing it now! 😄

**Comment by tonicospinelli** [comment]
I closed the Issue... 😒  ropening!

**Comment by JC5** [comment]
Done!
