### ISSUE TITLE
Categories overview period diagram doesn't show all transactions

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#261]
When selecting a category ```categories/show/10/2016-04-01``` the categorychart doesn't show all the transactions. The list of transactions does show all the transactions.

**Comment by JC5** [comment]
I spotted some bugs rewriting code for both budgets and categories. The next release, 3.9.0 should fix those.

**Comment by JC5** [comment]
I'm closing this now because I believe it to be fixed. 3.9.0 should be released somewhere this week or maybe tomorrow.

Please let me know if the bug is still there once you've upgraded.
