### ISSUE TITLE
Not able to import CSV (ABN)

### ISSUE THREAD

**Issue by svenpool** [JC5/firefly-iii#263]
Hi, 

I'm unable to import CSV from the ABN. It has worked, but i wanted to look at my finances and after a git pull it stopped working. 

I get this error message;

```
> Whoops! An error occurred.
> Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> 
> Type error: Argument 1 passed to FireflyIII\Repositories\Currency\CurrencyRepository::find() must be of the type integer, string given, called in /var/www/html/firefly-iii/app/Helpers/Csv/Converter/CurrencyCode.php on line 26
```

I hope you can help me out. Looking forward to hear from you.

Regards,
Sven

**Comment by JC5** [comment]
I noticed similar errors coming from the demo site. I know where it's coming from and I'll push a fix soon!

**Comment by JC5** [comment]
Will be fixed in the next version.
