### ISSUE TITLE
Categories and transfer transactions

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#266]
```/categories/show/x ```

Shows the transactions inclusive the transfers, these are calculated as earned as spent, is this by design? If I really want to know what is earned I must substract the transfers from the calculated ```earned```.

**Comment by JC5** [comment]
It does indeed, but it should not. From the context of those pages, your asset accounts should be filtered away.

I'll look into it!

**Comment by JC5** [comment]
Pushed a fix for the next release, 3.9.1. Thanks!

**Comment by xzaz** [comment]
Same goes for the diagrams.

**Comment by JC5** [comment]
Damn I completely missed this. I'll look into it! :grinning:

**Comment by JC5** [comment]
Fixed the diagrams as well.
