### ISSUE TITLE
Removing money from a piggy bank results in a error

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#269]
If you need more information I can provide later today.

**Comment by JC5** [comment]
I think I fixed this one in development. I'll get back to you.

**Comment by xzaz** [comment]
Is this fixed in dev?

**Comment by JC5** [comment]
Yes. 3.9.1 should be released tonight. So if you thought of switching, just hang in there a little bit ;).

**Comment by xzaz** [comment]
Hehe, no need for switching, currently using FireFlyIII one year :)

**Comment by JC5** [comment]
3.9.1 has been released. Please let me know if this fixes the issue!

**Comment by xzaz** [comment]
Fixed
