### ISSUE TITLE
Lastpass breaks login functionality

### ISSUE THREAD

**Issue by BasLangenberg** [JC5/firefly-iii#270]
Hi there,

I'm currently reviewing your software and it looks very promising! Thanks for this. (Self hosted and open source was my criteria, found it on Tweakers.net)

I notice that when I try to create an account or try to login to the tool with a Lastpass enabled browser, the user creation or the login fails. The logging looks like this:

`[2016-06-05 11:51:20] production.ERROR: Swift_RfcComplianceException: Address in mailbox given [enter_your_email_here] does not comply with RFC 2822, 3.6.2. in /opt/firefly-iii/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:348`

You might want to look into that. Let me know if you want me to test something.

Regards,
Bas

**Comment by JC5** [comment]
Your instance is not configured correctly. You might want to look into that
;).

**Comment by BasLangenberg** [comment]
I don't get why that would be the case. In a Lastpass enabled Chrome instance my logon attempt fails, and in Firefox without Lastpass I don't have any problems. Seems like a client bug to me.

**Comment by JC5** [comment]
enter_your_email_here, visible in your error message, is exactly what the
example .env file has as a default value for the email from value. Without
which, no email can be sent.

https://github.com/JC5/firefly-iii/blob/master/.env.example

Question is why your instance is trying to send email. Check out the logs
_before_ the enter_your_email_here message.
