### ISSUE TITLE
CSS does not work

### ISSUE THREAD

**Issue by Lugus** [JC5/firefly-iii#275]
Hi,

Directly after install, without any changes to apache2, I can't seem to get the CSS to work.

It's an install on a clean debian jessie server. Everything installed perfectly, but as soon as I go to the landing page the css won't load. I am unsure if there are any specific settings i should change on a clean apache2 install?

Error in apache2 log:

[Sat Jun 25 15:54:01.239796 2016] [:error] [pid 8147] [client *.*.*.*:58185] PHP Fatal error:  Uncaught Error: Call to undefined function bcscale() in /var/www/html/firefly-iii/bootstrap/app.php:16\nStack trace:\n#0 /var/www/html/firefly-iii/public/index.php(37): require_once()\n#1 {main}\n  thrown in /var/www/html/firefly-iii/bootstrap/app.php on line 16

I did install php7.0-bcmath

Update: Running apache2 in "notice" logging mode, I see this:

"GET /firefly-iii/public/index.php/lib/bootstrap/js/bootstrap.min.js HTTP/1.1" 404 6081 "http://192.168.1.14/firefly-iii/public/index.php/new-user" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
192.168.1.21 - - [25/Jun/2016:18:17:45 +0200] 

"GET /firefly-iii/public/index.php/js/lib/accounting.min.js HTTP/1.1" 404 6081 

"GET /firefly-iii/public/index.php/js/lib/bootstrap-tour.min.js HTTP/1.1" 404 6081 

"GET /firefly-iii/public/index.php/js/ff/help.js HTTP/1.1" 404 6081 

as if all those files can't be found.

**Comment by JC5** [comment]
* Check the source of the page you are on. What URL is in the ``<base href`` tag?
* What is the full URL of bootstrap.min.css in the source of the page?
* Are you getting a login page at least?

The GET things from your log makes me think that the configuration of either FF3 or your Apache is broken. But I'm not sure which one exactly.

**Comment by JC5** [comment]
Closing this issue because no feedback.

**Comment by Julianoe** [comment]
I had this same issue, CSS not used properly using behind a proxy. I had in fact forgotten the TRUSTED_PROXIES variable mentioned in #1179. It worked well once i added that to my docker-compose
