### ISSUE TITLE
Some transactions not showing

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#276]
I have a account:
``` 
/accounts/show/21/2016-06-01
```

Sometimes (?) the transactions are not the same as when I select the first page? Has this something to do with caching?

```
/accounts/show/21/2016-06-01?page=1
```

**Comment by JC5** [comment]
I've added an extra check that should prevent problems like this. It might be that the offset was a negative by mistake. 

I can't replicate your bug, but this should squash it nonetheless.

**Comment by JC5** [comment]
This bug may just have been fixed. ;)
