### ISSUE TITLE
Some errors after the installation

### ISSUE THREAD

**Issue by monsieurpouet** [JC5/firefly-iii#277]
Hi !

Before, thanks for the development ! It's is a great idea !
I've some issues after the installation. 
Example:

`[Tue Jul 12 10:50:49.758426 2016] [:error] [pid 26534] [client IP:PORT] PHP Fatal error:  Uncaught ErrorException: Missing argument 3 for Illuminate\\Session\\FileSessionHandler::__construct(), called in /var/www/firefly-iii/bootstrap/cache/compiled.php on line 12306 and defined in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php:41\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(41): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Missing argumen...', '/var/www/firefl...', 41, Array)\n#1 /var/www/firefly-iii/bootstrap/cache/compiled.php(12306): Illuminate\\Session\\FileSessionHandler->__construct(Object(Illuminate\\Filesystem\\Filesystem), '/var/www/firefl...')\n#2 /var/www/firefly-iii/bootstrap/cache/compiled.php(12301): Illuminate\\Session\\SessionManager->createNativeDriver()\n#3 /var/www/firefly-iii/bootstrap/cache/compiled.php(12402): Illuminate\\Session\\SessionManager->createFileDriver()\n#4 /var/www/firefly-iii/bootstrap/cache/compiled.php(12392): Illuminate\\Support\\Manager->createDr in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php on line 41
`

OR

`[Tue Jul 12 09:52:36.372277 2016] [:error] [pid 22031] [client IP:PORT] PHP Fatal error:  require(): Failed opening required '/var/www/firefly-iii/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/firefly-iii/bootstrap/autoload.php on line 20
`

Into Chrome: 

`Not Found
The requested URL /public/login was not found on this server.
`

And, Chrome don't find login.php into the public folder.
I've tried to update my composer dependencies to dev branch, doesn't work !
So, I'm lost ^^
Debian 8.5
PHP7.

Other information perhaps ?

**Comment by JC5** [comment]
Hi! Thanks for the compliment!

The first problem, I won't have until this weekend to look into your problem extensively, so here are some quick tips.

1. The first error seems to be generated in Laravel code exclusively. Try the following commands:

``rm -rf vendor/ composer.lock``
``composer update --no-scripts``
``composer update``
``php artisan clear-compiled``
``php artisan optimize``

2. That error is generated when you have not yet run ``composer update --no-scripts`` or a variant thereof.

3. This means that Apache cannot handle the URL scheme. Is "mod_rewrite" enabled? Can you surf to the following URL: http://your-installation/password/reset ? You should see a "password reset" form.

**Comment by monsieurpouet** [comment]
Hi !

Thanks for your help !

I've executed your command without any errors !

But I don't have the password form :/ And the rewrite module is activated.

This my apache vh (default installation) :

<VirtualHost *:80>
     # The ServerName directive sets the request scheme, hostname and 
port that
     # the server uses to identify itself. This is used when creating
     # redirection URLs. In the context of virtual hosts, the ServerName
     # specifies what hostname must appear in the request's Host: header to
     # match this virtual host. For the default virtual host (this file) 
this
     # value is not decisive as it is used as a last resort host regardless.
     # However, you must set it for any further virtual host explicitly.
     #ServerName www.example.com

     ServerAdmin webmaster@localhost
     DocumentRoot /var/www/firefly/public

     # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
     # error, crit, alert, emerg.
     # It is also possible to configure the loglevel for particular
     # modules, e.g.
     #LogLevel info ssl:warn

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined

     # For most configuration files from conf-available/, which are
     # enabled or disabled at a global level, it is possible to
     # include a line for only one particular virtual host. For example the
     # following line enables the CGI configuration for this host only
     # after it has been globally disabled with "a2disconf".
     #Include conf-available/serve-cgi-bin.conf
</VirtualHost>


But

**Comment by JC5** [comment]
What happens when you use this as the content of your ``.htaccess``?

```
Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]

```

**Comment by monsieurpouet** [comment]
It's WORKKKSSS !!

Don't forget the <Directory>  balise in the apache VH. But we can put 
the .htaccess content in the VH.

<Directory /var/www/firefly>
                 AllowOverride All
</Directory>

Very beautiful interface ! In french this would be better :D

I'll make a new installation to detect other error =)

**Comment by JC5** [comment]
Your description may contain any character. That is up to you of course. Does it give you an error?

If you wish for Firefly III to be in French, just join the translation project ;)

https://crowdin.com/project/firefly-iii

**Comment by JC5** [comment]
You can enable the French translations already present by changing a setting in your ``.env`` file:

``SHOW_INCOMPLETE_TRANSLATIONS=false``

>>

``SHOW_INCOMPLETE_TRANSLATIONS=true``

The language should become visible in your options.

**Comment by monsieurpouet** [comment]
Oh thanks ! 
I'll see that !

**Comment by muhahacz** [comment]
Why does not work, if i move content from .htaccess to virtualhost?

**Comment by JC5** [comment]
I don't know, sorry. According to the documentation the RewriteEngine command _should_ work in virtual host configurations. The same applies to the other content of the .htaccess file.

It would take some experimentation to find out what exactly is going on.

https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriteengine

**Comment by muhahacz** [comment]
it works ok, without .htaccess

```
<VirtualHost *:80>
        ServerName www.example.com
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/firefly/public

        <Directory /var/www/html/firefly/>
             AllowOverride All
             Options +FollowSymLinks
             Require all granted
             #Require host localhost
        </Directory>

         <Directory /var/www/html/firefly/public>
                RewriteEngine On
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule ^(.*)/$ /$1 [L,R=301]

                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^ index.php [L]
        </Directory>

        LogLevel alert rewrite:trace6

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

**Comment by JC5** [comment]
Very good! I am glad to hear it. I will remember your code in case of others with the same problems.

That log level, isn't that one that logs a lot of information?

**Comment by muhahacz** [comment]
its because of rewrite debugging. I forgot it here..
Ive just installed it on fresh Ubuntu 16.04 ( php-bcmath,php-intl was missing. Other dependencies are included in meta package apache2 ).
