### ISSUE TITLE
Installing firefly-iii with SQLite

### ISSUE THREAD

**Issue by skibbipl** [JC5/firefly-iii#279]
Hello,
I wanted to try firefly-iii with sqlite database - just to check if the app will work for me. I've followed installation guidelines and failed while running `php artisan migrate --seed --env=production` command. I've got following error:
```
 [InvalidArgumentException]
  Database (/var/www/firefly-iii/storage/database/testing.db) does not exist.
```
The error is pretty straightforward but I have no idea how to create `testing.db` file. My .env file has following configuration regarding database:
```
DB_CONNECTION=sqlite
DB_HOST=localhost
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```
I'm pretty sure I missed something, unfortunately installation instruction is very basic and doesn't contain too much information regarding database setup.
System: debian testing.

**Comment by JC5** [comment]
You can run this command:

``touch /var/www/firefly-iii/storage/database/testing.db``

Then, it should work. However, sqlite support may be not perfect: the next version will have new database commands which should work more smoothly.

**Comment by skibbipl** [comment]
Yeah, it seems something is totally wrong with SQLite support. After adding bank account my instance collapsed:
```
PDOException: SQLSTATE[HY000]: General error: 1 near "XOR": syntax error in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
...
Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 near "XOR": syntax error (SQL: select "transaction_journals".*, "transaction_types"."type" as "transaction_type_type", "transaction_currencies"."code" as "transaction_currency_code", "source"."account_id" as "source_account_id", "source"."amount" as "source_amount", "destination"."accoun
t_id" as "destination_account_id", "destination"."amount" as "destination_amount" from "transaction_journals" left join "transaction_types" on "transaction_types"."id" = "transaction_journals"."transaction_type_id" left join "transaction_currencies" on "transaction_currencies"."id" = "transaction_journals"."transaction_currency_id" left join "transactions" as "
source" on "source"."transaction_journal_id" = "transaction_journals"."id" and "source"."amount" < 0 left join "transactions" as "destination" on "destination"."transaction_journal_id" = "transaction_journals"."id" and "destination"."amount" > 0 where "transaction_journals"."user_id" = 1 and "transaction_journals"."user_id" is not null and "transaction_journals
"."date" <= 2016-07-31 00:00:00 and "transaction_journals"."date" >= 2016-07-01 00:00:00 and (source.account_id in (1) XOR destination.account_id in (1)) and "transaction_journals"."deleted_at" is null group by "transaction_journals"."id" order by "transaction_journals"."date" desc, "transaction_journals"."order" asc, "transaction_journals"."id" desc) in /var/w
ww/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:680
```
Are you interested in debugging this issue or I can close this ticket?

**Comment by JC5** [comment]
Well, of XOR is not supported I'm not sure I can get SQLite to work properly in a timely fashion. I'll have to rebuild the query to do the same but not use XOR.

**Comment by skibbipl** [comment]
If you need some info for debugging let me know. I installed firefly just for testing purposes so I can share the broken database or something.
Anyway I will have to setup a proper database to test the app further.

**Comment by JC5** [comment]
I'm afraid so, yes. I have sqlite available sometime I'll look into the
problem. Thanks for catching this one!
