### ISSUE TITLE
Error while transactions bulk update

### ISSUE THREAD

**Issue by stickgrinder** [JC5/firefly-iii#280]
I tried to edit multiple selected transactions from the Withdrawal list.
I landed on the multiline form, changed the values I intended and on form submission I got the error:

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is: 

Undefined index: source_account_id 
```

**Comment by stickgrinder** [comment]
I got a mail with a detailed error reporting (hey, great!!!).
Here it is, if it's of any help.

```
 Firefly III ran into an error: Undefined index: source_account_id
The error was of type "ErrorException".

The error occured on/at: Sat, 16 Jul 2016 18:07:30 +0000.
This error occured in file /var/apps/heterogenius.it/finance/app/Repositories/Journal/JournalRepository.php on line 550 with code 0.

The error was encountered by user #1, ----CENSORED----.

The IP address related to this error is: ----CENSORED----

The full stacktrace is below. If you think this is a bug in Firefly III, you can forward this message to thegrumpydictator@gmail.com. This can help fix the bug you just encountered.

If you prefer, you can also open a new issue on Github.
The full stacktrace is below:
``` 

Too bad the stacktrace is not there (it may be me not having properly debug settings for my PHP configuration?)

I'll try to check into it if I have some spare time.
Thanks :)

**Comment by JC5** [comment]
Getting the line number from the email message works just fine, thanks! 😁 

I'll get on it tomorrow, see what's happening.

**Comment by stickgrinder** [comment]
If you need any help/test/context info by me, let me know. :)
