### ISSUE TITLE
Getting asian characters in console output while installing

### ISSUE THREAD

**Issue by jkesseler** [JC5/firefly-iii#281]
I'm trying to install Firefly-III in vagrant on [a php7 image](https://github.com/rlerdorf/php7dev). It seems to have all the requirements but I get unexpected console output during installation

After running `composer install --no-dev`
![console](https://snag.gy/Yo7mcs.jpg)

After running `php artisan migrate --seed --env=production`
![console](https://snag.gy/Dl5Rsr.jpg)
![console](https://snag.gy/gCorbm.jpg)

This is what the page looks like in a browser
![browser](https://snag.gy/HyQnYr.jpg)

When running `composer install` the following error is shown:
```
Segmentation fault
Script php artisan firefly:upgrade-instructions handling the post-install-cmd event returned with error code 139
```

**Comment by JC5** [comment]
Lol I have no clue. I've never seen this. But segmentation faults are generally bad, really bad, and I suspect your VM isn't really stable.

I would suggest getting a vanilla VM with the latest Ubuntu, which should include PHP7, and follow the installation guide.

https://jc5.github.io/firefly-iii/installation-guide/

For PHP7

```
sudo apt-get install -y php7.0 php7.0-cli php7.0-common php7.0-fpm php7.0-mysql php7.0-curl php7.0-gd php7.0-imap php7.0-intl php7.0-json php7.0-mcrypt php7.0-readline php7.0-tidy php7.0-zip php7.0-bcmath php7.0-xml php7.0-mbstring php7.0-sqlite php7.0-bz2
```
