### ISSUE TITLE
Transaction editing broken

### ISSUE THREAD

**Issue by niekvanderkooy** [JC5/firefly-iii#284]
When trying to edit a transaction I get `Type error: Return value of FireflyIII\Support\Steam::phpBytes() must be of the type integer, string returned`

Probably fixable by returning `intval($string)` instead of `$string` from `FireflyIII\Support\Steam::phpBytes()`, but cannot get a dev environment up and running to investigate it (See #283)

**Comment by JC5** [comment]
Good catch! I haven't run into this one myself yet. But a fix is on the way!
