### ISSUE TITLE
Return here After storing transaction

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#285]
The function "Return here, After storing, return here to create another one." works but doesn't emtpy the fields for the next transaction.

**Comment by JC5** [comment]
It isn't supposed to. 😁

**Comment by xzaz** [comment]
So what's the quickest way besides import to bulk insert manually transactions?

**Comment by JC5** [comment]
Apologies, I missed this completely.

There isn't. I added the feature to make it easier to quickly enter transactions; old values are kept so you don't need to reenter everything all the time.
