### ISSUE TITLE
404 not found 

### ISSUE THREAD

**Issue by mrdeadlocked** [JC5/firefly-iii#287]
I'm not sure what all you'll need but here's from my nginx log. When I try to load firefly for the first time nginx has this erro "2016/08/07 06:09:41 [error] 1673#0: *14 open() "/var/www/html/firefly/public/login" failed (2: No such file or directory), client: 192.168.1.131, server: 192.168.1.205:8080, request: "GET /login HTTP/1.1", host: "192.168.1.205:8080"" What other logs/info will be helpful?

**Comment by JC5** [comment]
I think that nginx is not configured correctly. The /login URL means that Firefly works. It can see you have no session and wants you to login/register. But even though nginx can find / (the index) it cannot find /login (which is an url that doesn't really match a file).

This is my nginx config file. Try to match yours to it. And it might just start working. Don't forget to reload nginx.

```
server {
	listen 80;
	listen [::]:80;
        # pass the PHP scripts to FastCGI server listening on the php-fpm socket
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }

	root /sites/firefly-iii/public;

	client_max_body_size 300M;
    index index.php index.html index.htm;

	server_name firefly.app;

	location / {
        try_files $uri $uri/ /index.php?$query_string;
        autoindex on;
        sendfile off;
	}

}
```

**Comment by mrdeadlocked** [comment]
Yep. I had just found that in another issue and now im at a login. X.X Thanks. LoL my PHP info wasnt setup properly.

**Comment by mrdeadlocked** [comment]
http://pastebin.com/0b4rKBNv I've now got this warning on my main page when i login

**Comment by JC5** [comment]
Check the .env file, or create it by copying .env.example and fill in an
email address.

**Comment by mrdeadlocked** [comment]
i managed to get the mail error fixed by adding mail setting to my .env, but I somehow deleted the default currency and now I get this.


Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Type error: Return value of FireflyIII\Support\Amount::getDefaultCurrency() must be an instance of FireflyIII\Models\TransactionCurrency, null returned.

Anyway to reset defaults?

**Comment by JC5** [comment]
Reinstall, or run php artisan migrate:refresh --seed. You'll lose everything.

As an alternative, create a new entry in the table transaction_currencies.

Make created_at and updated_at something like this: 2016-08-08 22:00:00. Leave deleted_at blank. Then:

code: EUR
name: Euro
symbol: €

**Comment by soudaburger** [comment]
PHPinfo and nginx config below.  I am having the same issue from a fresh Centos 7 install.  I can get nginx to redirect to 'login' but 'login' page is blank and no valid code is returned.

`System	Linux firefly.app 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64
Build Date	Jul 21 2016 15:45:19
Server API	FPM/FastCGI
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/etc
Loaded Configuration File	/etc/php.ini
Scan this dir for additional .ini files	/etc/php.d
Additional .ini files parsed	/etc/php.d/bcmath.ini, /etc/php.d/bz2.ini, /etc/php.d/calendar.ini, /etc/php.d/ctype.ini, /etc/php.d/curl.ini, /etc/php.d/dom.ini, /etc/php.d/exif.ini, /etc/php.d/fileinfo.ini, /etc/php.d/ftp.ini, /etc/php.d/gd.ini, /etc/php.d/gettext.ini, /etc/php.d/gmp.ini, /etc/php.d/iconv.ini, /etc/php.d/intl.ini, /etc/php.d/json.ini, /etc/php.d/mbstring.ini, /etc/php.d/mcrypt.ini, /etc/php.d/mysqli.ini, /etc/php.d/pdo.ini, /etc/php.d/pdo_mysql.ini, /etc/php.d/pdo_sqlite.ini, /etc/php.d/phar.ini, /etc/php.d/shmop.ini, /etc/php.d/simplexml.ini, /etc/php.d/sockets.ini, /etc/php.d/sqlite3.ini, /etc/php.d/tokenizer.ini, /etc/php.d/xml.ini, /etc/php.d/xml_wddx.ini, /etc/php.d/xmlreader.ini, /etc/php.d/xmlwriter.ini, /etc/php.d/xsl.ini, /etc/php.d/zip.ini
PHP API	20151012
PHP Extension	20151012
Zend Extension	320151012
Zend Extension Build	API320151012,NTS
PHP Extension Build	API20151012,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	disabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	enabled
Registered PHP Streams	https, ftps, compress.zlib, php, file, glob, data, http, ftp, compress.bzip2, phar, zip
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, bzip2.*, convert.iconv.*, mcrypt.*, mdecrypt.*`

`server {
    listen 80;
    listen [::]:80;
        # pass the PHP scripts to FastCGI server listening on the php-fpm socket
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }
    root /sites/firefly-iii;
    access_log /var/log/nginx/firefly_access.log;
    error_log /var/log/nginx/firefly_error.log;

    client_max_body_size 300M;
    index index.php index.html index.htm;

    server_name firefly.app;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        autoindex on;
        sendfile off;
    }

}`

**Comment by soudaburger** [comment]
Figured it out!!!! Only took me like two days...

You have to DISABLE or set to PERMISSIVE SELINUX BEFORE configuring ANYTHING.  Then Reboot.  Then run the installation.  Woot!
