### ISSUE TITLE
Error when importing ING data

### ISSUE THREAD

**Issue by notliable** [JC5/firefly-iii#289]
After uploading my CSV and specification, ```/csv/process``` yields:
```
FireflyIII
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Type error: Return value of FireflyIII\Helpers\Csv\PostProcessing\OpposingAccount::process() must be of the type array, null returned
```

Taking a quick logs and at the code, it seems line 53 of OpposingAccount.php returns null where the return type is hinted to be an array. Excerpt from the code:
```
    public function process(): array
    {
    ....
    ....
        $result = $this->checkNameString();
        if (!is_null($result)) {
            return $result;
        }
        return null;
    }
```

**Comment by JC5** [comment]
Yes, I've seen other people having this problem as well.

One of these days, the next version of Firefly will be released, which should solve most import problems.

**Comment by notliable** [comment]
Great ;-) I am sincerely enjoying this gem of software.
