### ISSUE TITLE
Behind reverse proxy, redirects to IP address

### ISSUE THREAD

**Issue by dfiel** [JC5/firefly-iii#290]
I have my Firefly instance being hosted by nginx at 10.0.1.46. I have a front-facing Caddy server, which is set to proxy back to the correct IP address. This configuration works with other sites.

When trying to access the FQDN, Firefly redirects the browser to 10.0.1.46. What is causing this?

**Comment by JC5** [comment]
I think it has to do with this:

http://stackoverflow.com/questions/29912997/laravel-routes-behind-reverse-proxy

**Comment by dfiel** [comment]
Trying either of the fixes in that thread just gives me 500 errors when I try to access it from the domain or the internal IP 😕

**Comment by dfiel** [comment]
No fix?

**Comment by JC5** [comment]
Sorry mate, haven't had the time yet. I'm abroad for a week and I'll look
into it.

**Comment by dfiel** [comment]
Quite alright, just wondering

**Comment by JC5** [comment]
The problem has been solved. Please see the example configuration file in the next release for "APP_FORCE_ROOT". Fill in the URL you expect Firefly III at (in full, so for example: "http://example.com" without the quotes).

That should fix it.

**Comment by dfiel** [comment]
Great, I'll try it now!

**Comment by DenBeke** [comment]
Stumbled upon this issue and hoped `APP_FORCE_ROOT` would solve the issue, but it seems that `APP_FORCE_ROOT` is removed.
Using `TRUSTED_PROXIES=**`  did the trick for me.
