### ISSUE TITLE
After installation login not found

### ISSUE THREAD

**Issue by Gamebase32** [JC5/firefly-iii#299]
I Followed the installation guide on your website, but got the following error:
404 Not Found
Not Found
The requested URL /login was not found on this server.
Apache/2.4.18 (Ubuntu) Server at someserver.domain.test Port 80

**Comment by Gamebase32** [comment]
Figured it out ;)
By default in Ubuntu 16.04.1 LTS the Allow Override in the apache2.conf for /var/www is None. If you change that to All it works. Had the same problem with BookStack on this server.

**Comment by JC5** [comment]
Nice catch!

I have updated the installation manual to reflect this.

**Comment by Gamebase32** [comment]
Today I tried to install Firefly again on a clean testbox running Ubuntu 16.04 LTS and came across some other problems. Do you want me to make an issue and reply or send you the details?

**Comment by JC5** [comment]
You can make an issue and put them all in. That way, I can expand the installation manual and refer to your issue. Thanks!
