### ISSUE TITLE
Application allows the default currency to be deleted causing system crash

### ISSUE THREAD

**Issue by mondjef** [JC5/firefly-iii#308]
User is able to delete currency that is set as default which causing application to raise an error.  Can be fixed database side but should not allow the action on the front end.  In addition all currencies can be deleted resulting the same error being raised by the application.  I think the business rules around currencies should be that there must be at least one currency, if only one currency it is automatically set as default, and cannot delete a currency if it is currently set as default.

**Comment by JC5** [comment]
Lol. 

It should only be possible to do so when you have no transactions at all, am I right? Then at least that part works. 

I'll build in a check.

**Comment by JC5** [comment]
Oh I'm on mobile so I can't edit. Did it work when you ran the migration again?

**Comment by mondjef** [comment]
yes it was when I had no transactions at all.  Thanks

**Comment by mondjef** [comment]
ran the migration last night and your fix worked.  Thanks
