### ISSUE TITLE
Bug with the piggybank and nullvalues database

### ISSUE THREAD

**Issue by leander091** [JC5/firefly-iii#309]
The targetdate in the piggybank function is defined as an optional field but the linked databasecolumn don't accept a null value.
.

**Comment by leander091** [comment]
![bug_database](https://cloud.githubusercontent.com/assets/5831104/18398320/8ba6e5e4-76cc-11e6-923b-8f79af23eaec.png)

**Comment by JC5** [comment]
Damn, I must have forgotten that one. I apologize!

I will correct the migration files for the next release, and then it should
not be a problem anymore. Would that be OK?

**Comment by JC5** [comment]
Mmm. Which version did you instal? The piggy banks table has a nullable() targetdate. You should be fine :).

**Comment by leander091** [comment]
I am using the 3.10.2  version.

**Comment by JC5** [comment]
Mmmm. 3.10.2 contains the correct migration data. Are you running MySQL?

You could make the field nullable yourself, and you should be good. In the mean time, I will try to find out what went wrong.

**Comment by leander091** [comment]
Yeah i am running a mysql server.

**Comment by leander091** [comment]
I don't no exactly  why but with the latest update and a clean install the value is right now.
![screenshot_20160911_132452](https://cloud.githubusercontent.com/assets/5831104/18416938/3a595052-7823-11e6-86aa-f95681080921.png)

**Comment by JC5** [comment]
Glad to hear it! I hope nobody else will suffer from it. Let me know if you're running into anything else, and I'll get right on it. Thanks!
