### ISSUE TITLE
Installation on Debian with Apache and pre-existing vhost

### ISSUE THREAD

**Issue by qligier** [JC5/firefly-iii#313]
Hey,

I went through the whole installation of Firefly III, which was not so easy.

My server was running Apache 2.4.10 with PHP 5.6 and libapache2-mod-php5. My domain (_my.domain.com_) already had a DocumentRoot (_/var/www/my.domain.com/public_html/_) and I didn't want to change it, so I wanted to serve Firefly III through an alias (_my.domain.com/firefly/_ and not _my.domain.com/firefly/public/_). 

The first step was to install PHP 7. With Debian Jessie, I had to add the following repository:
```bash
quentin@server:~$ cat /etc/apt/sources.list.d/dotdeb.list
# Dot deb Repository. See www.dotdeb.org
deb http://packages.dotdeb.org jessie all
deb-src http://packages.dotdeb.org jessie all
quentin@server:~$ wget https://www.dotdeb.org/dotdeb.gpg
quentin@server:~$ sudo apt-key add dotdeb.gpg
quentin@server:~$ sudo apt-get update
```

I cloned the repository in _/var/www/my.domain.com/firefly-iii/_. After solving a few issues with Apache and PHP, my Apache config looked like this:
```apache
<VirtualHost 1.2.3.4:443>
    ServerName my domain.com
    DocumentRoot /var/www/my.domain.com/public_html/

    # Firefly III
    Alias /firefly /var/www/my.domain.com/firefly-iii/public
    <Directory /var/www/my.domain.com/firefly-iii/public/>
        Options -Indexes +FollowSymlinks
        Require all granted

        # No need for AllowOverride All as the rules are here
        RewriteEngine On
        # Must match the Alias
        RewriteBase /firefly/
        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)/$ /$1 [L,R=301]
        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]

        <FilesMatch \.php$>
            # Must match the "listen" rule in /etc/php/7.0/fpm/pool.d/www.conf
            SetHandler "proxy:unix:/run/php/php7.0-fpm.sock|fcgi://localhost/"
        </FilesMatch>
    </Directory>
```

Without the `RewriteBase /firefly/` rule, I had a 404 error when browsing _my.domain.com/firefly/login_ and I saw the page without resources (JS, CSS, ...) when browsing _my.domain.com/firefly/index.php/login_.

This configuration allows PHP 7 to process all `.php` files inside Firefly III directory but not other files (_my.domain.com/index.php_ is still processed by PHP 5.6).

I was able to register but encountered the following error when logged in:
```
Type error: Return value of FireflyIII\Support\Amount::getDefaultCurrency() must be an instance of FireflyIII\Models\TransactionCurrency, null returned.
```
In my _.env_ I had chosen CHF as DEFAULT_CURRENCY. Inserting a new row in `transaction_currencies` with `code=CHF, name=Swiss franc, symbol=CHF` and refreshing the page did the trick.

The installation guide was pretty good but it could be improved:
* Filling the `.env` file isn't easy because the possible values of some variables aren't known (DB_CONNECTION, MAIL_DRIVER, MAIL_ENCRYPTION by example).
* What does the APP_FORCE_ROOT variable?
* If there is only one .htaccess file, why don't you add the rules directly in Apache configuration, as it already needs to be modified? It's always better to have `AllowOverride None`.

Hope this could help!

**Comment by JC5** [comment]
Hi! Thanks for the extended post!

Let's go point by point through your issues.

- First of all, my compliments to your Apache configuration. It can be pretty complex to configure both PHP 7.0 and PHP 5.6 on the same machine.
- The default currency you've changed in your .env file is the absolute fallback in case everything is broken, or when a new user registers. You can change it to CHF of course, but it doesn't really matter until you start hosting Firefly for external users. If you visit ``/currency`` you'll see all the options you'll ever need, and you can leave the EUR setting for what it is.
- APP_FORCE_ROOT allows you to force Firefly to serve all it's URL's over a different domain. In the case of reverse proxy's, the instance hosting Firefly doesn't really know its external URL, and it will usually revert to http://localhost/. This setting allows you to force Firefly to use http://whatever/.
- The .htaccess file stays. Many users are using nginx or other systems. Editing Apache is necessary indeed to set ``AllowOverride All`` but many users use virtual machines such as those offered by Docker and Vagrant and thus care little for the security concerns of that particular setting.
- I will certainly extend the installation guide to include more information about the ``.env`` file. The DB_CONNECTION and possibly MAIL_DRIVER, I secretly think a user must be able to fill those in himself. Having said that, it does not hurt to help.

I'm glad you managed to install Firefly III, and I hope you'll enjoy it. Please send all the feedback you have my way. In the mean time, I will update a certain installation guide ;)

**Comment by qligier** [comment]
> The default currency you've changed in your .env file is the absolute fallback in case everything is broken, or when a new user registers. You can change it to CHF of course, but it doesn't really matter until you start hosting Firefly for external users. If you visit /currency you'll see all the options you'll ever need, and you can leave the EUR setting for what it is.

That's true but I didn't know that at the time I modified the `.env` file.

> I will certainly extend the installation guide to include more information about the .env file. The DB_CONNECTION and possibly MAIL_DRIVER, I secretly think a user must be able to fill those in himself. Having said that, it does not hurt to help.

After having found the swiftmailer folder, it was clear how to fill MAIL_DRIVER and MAIL_ENCRYPTION. Finding dbal has been harder. It would help to have comments in the `.env` file, telling which variables configure which library.

**Comment by JC5** [comment]
I'll make sure that it will be easier to configure the file. Options will be moved from the file anyway, and the others will get instructions.

**Comment by JC5** [comment]
I've extended the installation manual! :D
