### ISSUE TITLE
Charts and locale

### ISSUE THREAD

**Issue by qligier** [JC5/firefly-iii#316]
Hey,
I've an issue with charts: the thousands separator (a single quote in my locale) is shown as its html entity (&#&thinsp;039;) both in Chrome and Firefox. They're thus hard to read. 
Changing the DEFAULT_LANGUAGE back to en_US or changing the Accept-Language header didn't solve the issue.
Thanks,
Quentin

**Comment by JC5** [comment]
Which locale is it, and where did you configure Firefly III to display it?

**Comment by qligier** [comment]
The locale is fr_CH. I set it in the DEFAULT_LANGUAGE variable at setup.

**Comment by JC5** [comment]
Ah, I see. Unfortunately, Firefly III does not support setting the locale this way. I'm glad that some of the libraries used are able to handle it, but that's more luck than anything. I'm pretty sure most other fields remained English, am I correct?

I'll see what I can do about the double escaping. But that field is not meant to be changed to just any locale, and Firefly might break in new and exciting ways.

**Comment by qligier** [comment]
That's right.
Using en_US is fine but I can't revert the setting, any idea why?

**Comment by JC5** [comment]
Try this on the command line: ``php artisan cache:clear``. And check your preferences, and set it to en_US as well.

**Comment by qligier** [comment]
In my preferences, there was no language checked. Choosing English has solved this chart issue.
Thanks!
