### ISSUE TITLE
-14.9 Amount Field Imported as 149.00

### ISSUE THREAD

**Issue by Mortalife** [JC5/firefly-iii#318]
I've been attempting to import my transaction into Firefly.

For some reason integers are not being parsed corretly.

Any #.# value is being added as a ##.00 value. 
##.## values are added correctly.

**Comment by Mortalife** [comment]
`$decimalPosition = $len - 3;`

Hard coded decimal location

**Comment by Mortalife** [comment]
#319

**Comment by JC5** [comment]
Hah! I knew it would not be long before somebody came to me with a .0 decimal position. I'm fairly sure that today or tomorrow, the .000 will also be posted. Oh well ;)

Thanks for noticing, and thank you for the fix. I must ask you, could you re-submit your fix and send it to the _develop_ branch? The master branch is usually reserved for releases only.

The next version of Firefly will probably be 4.0.0 and will be released somewhere this week. It will include your fix as well!
