### ISSUE TITLE
Arbitrary notes field on piggy banks

### ISSUE THREAD

**Issue by telyn** [JC5/firefly-iii#350]
I use piggy banks to allow me to budget for buying stuff, some of which comes in many parts (for instance, I want to rebuild a server, which involves buying a CPU, motherboard, case, RAM and power supply)

It'd be great to have a text field to add arbitrary notes to piggy banks so that I could keep links to the parts I'm intending to buy once I've saved the money. That way all my budgeting and planning is in one place and I don't have to remember where I saved the list of links.

This may be useful in other places, so perhaps the way to implement it would be to add a notes table to the database and have a possibly-NULL note_id column on the piggy bank table. That way if notes were wanted on other things (transactions?) it'd be trivial to add them. Maybe there's already a notes table, I've not actually looked I'm afraid! Implementation details are down to the implementor anyway, that's just a suggestion.

Apologies if this has already been implemented, I'm running on a slightly old version (February or so?) because I had trouble getting PHP 7 working under docker. I will give it another bash sooner or later, and if I can get a production deploy with PHP 7 I'll hack this feature in myself and submit a PR 😄

**Comment by JC5** [comment]
There isn't yet, but it is both a good idea to add notes and to add notes in such a way that other objects can enjoy their presence as well! I'll keep it in mind!

**Comment by JC5** [comment]
Firefly 4.1 will support notes!

**Comment by telyn** [comment]
Aww yeah! Thank you for doing this! :heart:

**Comment by JC5** [comment]
This is just a basic implementation. 4.1.1 will support Markdown, and it will gives the notes a better spot to be displayed.
