### ISSUE TITLE
Tab delimiter is not properly loaded from import configuration

### ISSUE THREAD

**Issue by roberthorlings** [JC5/firefly-iii#355]
When downloading the import configuration file, a tab delimiter is stored as '\t'. However, when loading the import configuration file, the delimiter isn't loaded properly and the default ',' delimiter is selected. I assume this is caused by the selectbox in the configuration screen using  'tab' to denote the option, as opposed to the configuration file using '\t' to denote it.

**Comment by JC5** [comment]
Good call! There's a fix in the develop branch
