### ISSUE TITLE
Importing data fails

### ISSUE THREAD

**Issue by muhahacz** [JC5/firefly-iii#357]
Hello,
Im trying to import sample data (http://www.eucty.cz/documents/importDataCS.csv), but it fails on: Type error: hash() expects parameter 2 to be string, boolean given
log@http://pastebin.com/haThhdUV

First row is header. First column is describtion, second date and third is amount.
Any solution?
Thanks

**Comment by JC5** [comment]
The file contains "special" characters, like ú, è, á, and í. This is not a problem by itself.

However, the file is probably stored as a "Windows-1252" encoded file, or possibly another type of encoding. Perhaps ANSI? There are many possibilities. 

Firefly III assumes "UTF-8".

If you have the program Notepad++, open your CSV file and find the option to convert to UTF-8 in the menu "Encoding".

Here is an example with the content converted to UTF-8. You can see that the special characters now work:

![image](https://cloud.githubusercontent.com/assets/5889984/19390789/e6ee7a3e-9229-11e6-8c8f-21f16f2e6432.png)

**Comment by JC5** [comment]
Let me know if you run into more problems! 👍
