### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by dvanp** [JC5/firefly-iii#361]
I've set up a VM (Ubuntu 16.04, PHP7) for Firefly today and it seems to work very well, except for some small parts. The issues I'm having seem related, so I'll post them here together.

- Changing the amount of budgets doesn't work. The amount resets to 1, sometimes 2 after leaving the Budgets page. The associated error: 
> call_user_func_array() expects parameter 1 to be a valid callback, class 'FireflyIII\Handlers\Events\BudgetEventHandler' does not have a method 'updateRepetition'

- When logging out, I get the following error: 
> call_user_func_array() expects parameter 1 to be a valid callback, class 'FireflyIII\Handlers\Events\UserEventHandler' does not have a method 'logoutUser'

Thanks!

**Comment by JC5** [comment]
I've just recently pushed an update which I hoped would not change anything. I was pretty sure it did not break anything. Alas, not sure enough.

I shall push a new version and you can use that one instead. I apologize for the inconvenience!

**Comment by JC5** [comment]
This should fix the problem you've encountered. You can upgrade using ``git pull`` in the ``/firefly-iii/`` map.

**Comment by dvanp** [comment]
Already `pull`ing! Thanks a lot!
