### ISSUE TITLE
Splitting transactions doesn't work

### ISSUE THREAD

**Issue by HungryFeline** [JC5/firefly-iii#367]
![firefly_iii_-_2016-10-29_14 58 53](https://cloud.githubusercontent.com/assets/782759/19829759/7416c49a-9dea-11e6-8c7e-0e9137f52ab7.png)

Issue seems to be that [Line 265 of app/Http/Controllers/Transaction/SplitController.php](https://github.com/JC5/firefly-iii/blob/master/app/Http/Controllers/Transaction/SplitController.php#L265) expects an array "transactions", but [Line 139 of public/js/ff/split/journal/from-store.js](https://github.com/JC5/firefly-iii/blob/master/public/js/ff/split/journal/from-store.js#L139) (and also line 145, 151, 157, 163 & 169) replaces the name into "transaction". Adding "s" 6 times helps to fix the error above.

But now after submitting, nothing seems to be stored. The page loads again (with "After updating, return here." checked) and the Splits is just one row again.

**Comment by JC5** [comment]
Good find!

The fix you suggested does indeed work. It will be included in the next version of Firefly.

https://github.com/JC5/firefly-iii/commit/a79a8c88749b8de56f487281c5394ce581237b20

**Comment by HungryFeline** [comment]
Wow, that was fast, thank you! I also tested it and adding splits works fine now!

Awesome!
