### ISSUE TITLE
Unable to split transaction after upgrade to 4.1.5

### ISSUE THREAD

**Issue by ksmolder** [JC5/firefly-iii#371]
After upgrading to 4.1.5 (coming from 4.0.0), it is no longer possible to split a transaction into multiple parts. The "add another split" button does not insert a new row anymore. Nothing suspicious appears in the log file.

**Comment by JC5** [comment]
Try control or command F5, does that work?

**Comment by ksmolder** [comment]
Completely reloading the page was indeed sufficient for getting it back to work... Will do that next time before filing an issue.

Thanks for fast feedback
