### ISSUE TITLE
Recreating a currency after having deleted it previously doesn't work

### ISSUE THREAD

**Issue by schoentoon** [JC5/firefly-iii#375]
During my initial setup I deleted all currencies that I wouldn't need, so I deleted the dollar. Now as I'm trying to add the dollar again I get error messages that the '$' symbol is already taken. And the the code 'USD' is already taken, while these are not in the list of currencies. Tested with 4.1.5.

**Comment by JC5** [comment]
I'll make sure that you can recreate currencies. In the mean time, open the table ``transaction_currencies`` in your favourite database tool and set the column "deleted_at" to ``NULL``. Make sure it's NULL, not "0000-00-00 00:00:00".

That should redisplay the transaction currency.

**Comment by schoentoon** [comment]
Thanks for the quick response, I can confirm that setting deleted_at to NULL works around this issue.
