### ISSUE TITLE
Expenses are not filtered on date range

### ISSUE THREAD

**Issue by 3mz3t** [JC5/firefly-iii#377]
Hi James,

Menu: Transactions->Expenses
Url: transactions/withdrawal

The expenses listed are not filtered by the date range set by the user on top of the screen.

It seems the same issue applies to transactions/transfers and transactions/deposit

Cheers,

3mz3t

**Comment by JC5** [comment]
Heya,

It's intentional, and meant to just be a list of transactions.

But it might be an idea to split them up like /accounts/show/x or categories/show/x

I'll get on it, shouldn't be difficult!
