### ISSUE TITLE
Commit 22a2fe3 breaks Firefly

### ISSUE THREAD

**Issue by dvanp** [JC5/firefly-iii#389]
I did a pull on the master branch today and ran into an issue: 

> Whoops, looks like something went wrong.

so I went tracing the issue back to the commit it first occurred and discovered that commit 22a2fe3 seems to be the problem.

Is there a log somewhere I can see what goes wrong? I checked the nginx log, but there's nothing there.

**Comment by JC5** [comment]
There are log files in `storage/logs`

If those are not detailed enough, open the `.env` file and change the log level to `debug`.

Also, run `composer install --no-dev` and `php artisan cache:clear` to make sure old caches are cleaned up.

**Comment by JC5** [comment]
Any news?

**Comment by dvanp** [comment]
Sorry, it was a caches problem indeed. Thanks!
