### ISSUE TITLE
Rule creates duplicate destination accounts

### ISSUE THREAD

**Issue by marcoveeneman** [JC5/firefly-iii#395]
Hi,

To merge the Albert Heijn related accounts into a single one i tried using the following transaction rule:
![image](https://cloud.githubusercontent.com/assets/4264614/20115236/c8f18ae4-a5f7-11e6-8735-c0f0768c8ed0.png)

This created 10s of different expense accounts named Albert Heijn, each account having a single transaction. I expected a single Albert Heijn account to be created with all the transactions belonging there. Re-running the rule group created another list of Albert Heijn accounts and made the older ones empty.

![image](https://cloud.githubusercontent.com/assets/4264614/20115534/e64c3cf0-a5f8-11e6-8ab6-db936c16ba9a.png)

I'm using version 4.1.6

**Comment by JC5** [comment]
Lol whoops. There should be a single one, yes. I'll check it out and push a fix. Skip the rule action for now, new release will be this weekend.

**Comment by marcoveeneman** [comment]
Thanks. I will wait for a fix then :)

**Comment by JC5** [comment]
If you want to fix this yourself to be able to continue, open the file called ``app/Rules/Actions/SetDestinationAccount.php``.

On [line 126](https://github.com/JC5/firefly-iii/blob/master/app/Rules/Actions/SetDestinationAccount.php#L126), you should find the word "REVENUE". Replace this word with EXPENSE, [like so](https://github.com/JC5/firefly-iii/commit/cf69333c6dbac32de554e382ac718a70ae35e032).

That should fix it.

**Comment by marcoveeneman** [comment]
Thank you for the quick fix! I can confirm this works.
I had to change the destination account to another name, e.g. 'Albert Heijn 2', to get all transactions in that single account.

**Comment by marcoveeneman** [comment]
Maybe a bit offtopic, but is there a way to select/delete multiple accounts at once, like transactions? I have a bunch of duplicate accounts left now.

**Comment by JC5** [comment]
I'm afraid not :(

**Comment by marcoveeneman** [comment]
Ok. I started to remove them by hand and now got this fatal error:

```
( ! ) Fatal error: Class Symfony\Component\Finder\Iterator\FileTypeFilterIterator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (FilterIterator::accept) in C:\wamp64\www\firefly-iii\vendor\symfony\finder\Iterator\FileTypeFilterIterator.php on line 19
Call Stack
#	Time	Memory	Function	Location
1	0.0010	369752	{main}( )	...\index.php:0
2	0.0360	3696224	Illuminate\Foundation\Http\Kernel->handle( )	...\index.php:62
3	0.0360	3696224	Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter( )	...\Kernel.php:116
4	0.0360	3720304	Illuminate\Foundation\Http\Kernel->bootstrap( )	...\Kernel.php:144
5	0.0360	3720304	Illuminate\Foundation\Application->bootstrapWith( )	...\Kernel.php:253
6	0.0516	3887872	Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap( )	...\Application.php:203
7	0.0516	3904728	Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles( )	...\LoadConfiguration.php:38
8	0.0516	3904728	Illuminate\Foundation\Bootstrap\LoadConfiguration->getConfigurationFiles( )	...\LoadConfiguration.php:59
9	0.0516	3980008	Symfony\Component\Finder\Finder->files( )	...\LoadConfiguration.php:76
10	0.0516	3980008	spl_autoload_call ( )	...\Finder.php:101
11	0.0516	3980184	Composer\Autoload\ClassLoader->loadClass( )	...\Finder.php:101
12	0.0516	3980184	Composer\Autoload\includeFile( )	...\ClassLoader.php:301
13	0.0516	3986136	include( 'C:\wamp64\www\firefly-iii\vendor\symfony\finder\Iterator\FileTypeFilterIterator.php' )	...\ClassLoader.php:414
```

**Comment by JC5** [comment]
I've never seen that one before. Try

**Comment by marcoveeneman** [comment]
I ran both commands and now get the following error:

```
( ! ) Fatal error: Class Symfony\Component\Finder\Iterator\PathFilterIterator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (FilterIterator::accept) in C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php on line 16874
Call Stack
#	Time	Memory	Function	Location
1	0.0000	367144	{main}( )	...\index.php:0
2	0.0000	369008	require( 'C:\wamp64\www\firefly-iii\bootstrap\autoload.php' )	...\index.php:31
```
