### ISSUE TITLE
Dedicated category report

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#396]
Select a category or multiple ones:

- Show some kind of summary of expenses. Income. Number of transactions. Accounts involved (asset and others). Average expense, average income?
- Pie chart for money in and out: the selected categories make up 100% together. Optionally, include everything else (for comparison)
- Show income / expenses per period. Differs per report: month = per day, year = per month, multi-year = per year. In a bar chart, possibly grouped by expense/revenue account.
- Bars in bar chart could be clickable to show a list of expense/revenue accounts (so the detail isn't in the chart but a list below it).
- Possibly a full list of expenses / incomes? May depend on period.

**Comment by xzaz** [comment]
I really need this; for Crowdfunding I have a lot of Revenue accounts that I keep track of.

**Comment by JC5** [comment]
Report v1 will be included in the next release.
