### ISSUE TITLE
Can not add balancing tag to income/revenue transaction

### ISSUE THREAD

**Issue by marcoveeneman** [JC5/firefly-iii#398]
Hi,

I can add an expense to a balancing tag but when i try to add the income/revenue transaction it won't save it.

**Comment by JC5** [comment]
Confirmed! I'll look into it

**Comment by JC5** [comment]
Wait no, you can't. You can only balance out transfers and expenses. My bad.

The idea is that you spend amount X and balance this out with money from another account (ie. your savings account).

**Comment by marcoveeneman** [comment]
Ah yes i understand, i'm sorry for the noise. What would you recommend to balance a refund for example?

**Comment by JC5** [comment]
No problem, no problem!

I always use the advance payments for those things, even though the name doesn't really match the goal. The idea is that you would pay a restaurant bill and people would pay you back. It should work for this occasion as well :)

**Comment by marcoveeneman** [comment]
I see, thanks for the hint :) I guess this issue can be closed.

**Comment by JC5** [comment]
Can do!

**Comment by marcoveeneman** [comment]
Hm i think i'm doing something wrong or this is really a bug.
I tried the advance payment tag but i can only add an expence OR an income/revenue, not both at the same time.

**Comment by JC5** [comment]
You found a bug! Fix will be live in the next version.
