### ISSUE TITLE
Call to undefined function FireflyIII\Http\Middleware\numfmt_create() 

### ISSUE THREAD

**Issue by schwalberich** [JC5/firefly-iii#413]
Hello,

after doing a git pull today, I am no longer able to access the firefly site.
After analzing the log I found out that there was an Issue with the sql User.
After updating the sql user to the correct Password, I know get following 
Message after Login directly:

Call to undefined function FireflyIII\Http\Middleware\numfmt_create() 

I checked my PHP installation, but php7.0-intl is at the current state and everything worked until 
yesterday

**Comment by JC5** [comment]
The function you mention is called [here](https://github.com/JC5/firefly-iii/blob/929d8b3adcd27f4825dcd8326212ccd925d9632d/app/Http/Middleware/Range.php#L115) where it is used to help Firefly format currencies.

Generally speaking, what might help are these commands (in order) in the directory where Firefly is installed.

```
php artisan cache:clear
rm -rf vendor
composer install --no-scripts
composer install
```

This should clear out and reset most of Firefly's internal systems. 

If this does not work:

Please create a phpinfo.php and place it in the public/ directory. The content of the file must be:

```
<?php
phpinfo();
```

Surfing to this file (/phpinfo.php) should show you if the intl module is indeed correctly installed and loaded.

Let me know if this works!

**Comment by schwalberich** [comment]
Hello again,

after your first steps didn't help me I found out in the phpinfo(), that for some reasons
php did use the wrong php instance, where of course intl wasn't installed.

After deleting the second php7 build and reboot everything, it now uses the correct php7 directory,
and firefly-iii is working again.

Thank you
