### ISSUE TITLE
Error when importing Rabobank CSV

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#416]
Hi,
I am using the Rabobank configuration from [here](https://github.com/firefly-iii/import-configurations/blob/master/nl/rabobank/default.json), but that gives me an error when importing this example file:

<code>
"IBAN2","EUR","20160101","C","1.43","0000000000","","20160104","","","Rente over periode","01-01-2015 t/m 31-12-2015","","","","","","",""
"IBAN2","EUR","20160129","C","40.00","IBAN1","J. TEST","20160129","","","Bijschrijving","","","","","","","",""
"IBAN2","EUR","20160817","C","10.00","IBAN1","J. TEST","20160818","","","Bijschrijving","","","","","","","",""
</code>

I anonimized the CSV of course.

I'm on master.
This is my stack trace:

<code>
FireflyIII
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Undefined offset: 5

Error

This error occured in file /var/www/site.com/public_html/app/Import/Specifics/RabobankDescription.php on line 48 with code 0.

Stack trace

#0 /var/www/site.com/public_html/app/Import/Specifics/RabobankDescription.php(48): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/fin.ja...', 48, Array)
#1 /var/www/site.com/public_html/app/Import/Setup/CsvSetup.php(460): FireflyIII\Import\Specifics\RabobankDescription->run(Array)
#2 /var/www/site.com/public_html/app/Import/Setup/CsvSetup.php(117): FireflyIII\Import\Setup\CsvSetup->getDataForColumnRoles()
#3 /var/www/site.com/public_html/app/Http/Controllers/ImportController.php(296): FireflyIII\Import\Setup\CsvSetup->getDataForSettings()
#4 [internal function]: FireflyIII\Http\Controllers\ImportController->settings(Object(FireflyIII\Models\ImportJob))
#5 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9389): call_user_func_array(Array, Array)
#6 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9416): Illuminate\Routing\Controller->callAction('settings', Array)
#7 /var/www/site.com/public_html/bootstrap/cache/compiled.php(8474): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\ImportController), 'settings')
#8 /var/www/site.com/public_html/bootstrap/cache/compiled.php(8455): Illuminate\Routing\Route->runController()
#9 /var/www/site.com/public_html/bootstrap/cache/compiled.php(8151): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/site.com/public_html/app/Http/Controllers/ImportController.php(50): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9866): FireflyIII\Http\Controllers\ImportController->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/site.com/public_html/app/Http/Controllers/Controller.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9866): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/site.com/public_html/app/Http/Middleware/Binder.php(55): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/site.com/public_html/app/Http/Middleware/Range.php(83): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/site.com/public_html/app/Http/Middleware/IsConfirmed.php(60): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): FireflyIII\Http\Middleware\IsConfirmed->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/site.com/public_html/app/Http/Middleware/AuthenticateTwoFactor.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/site.com/public_html/app/Http/Middleware/Authenticate.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9982): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/site.com/public_html/bootstrap/cache/compiled.php(3151): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/site.com/public_html/bootstrap/cache/compiled.php(13471): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/site.com/public_html/bootstrap/cache/compiled.php(11911): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/site.com/public_html/bootstrap/cache/compiled.php(13217): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/site.com/public_html/bootstrap/cache/compiled.php(13154): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9859): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/site.com/public_html/bootstrap/cache/compiled.php(8152): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/site.com/public_html/bootstrap/cache/compiled.php(8143): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /var/www/site.com/public_html/bootstrap/cache/compiled.php(8134): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /var/www/site.com/public_html/bootstrap/cache/compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#55 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/site.com/public_html/bootstrap/cache/compiled.php(3213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9874): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/site.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/site.com/public_html/bootstrap/cache/compiled.php(9859): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/site.com/public_html/bootstrap/cache/compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /var/www/site.com/public_html/bootstrap/cache/compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#62 /var/www/site.com/public_html/public/index.php(62): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#63 {main}</code>

Sorry for the bad formatting..

**Comment by JC5** [comment]
You're not the first one. Which version of FF are you running? The offset errors should be caught. Did you import your data using the "," separator and not the ";" separator (despite the configuration)?

**Comment by zjean** [comment]
Hi, 

I am on the latest  master. Will double check later tonight. Will check
the separator as well to be sure ;)




On Tue, Nov 22, 2016, at 20:32, James Cole wrote:

> You're not the first one. Which version of FF are you running? The
> offset errors should be caught. Did you import your data using the ","
> separator and not the ";" separator (despite the configuration)?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 


Links:

  1. https://github.com/JC5/firefly-iii/issues/416#issuecomment-262341461

**Comment by zjean** [comment]
Ah, the bug is possibly fixed in commit 75a524c which is not yet on the master branch.
I don't have a develop environment yet, so can't test it right now.
I double checked and used a comma as separator.

**Comment by JC5** [comment]
Apologies, I thought I released that code already. It'll be live this weekend.

I'll try to find the root cause. I'm not sure what is happening yet.

**Comment by zjean** [comment]
On develop this works.
