### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#418]
Hi,
I am testing the import functionality on my new develop environment an run into some issues:
- I am using these import files (renamed the config to .txt instead of .json to allow github-uploads).
[test1.txt](https://github.com/JC5/firefly-iii/files/610001/test1.txt)
[firefly-rabobank.txt](https://github.com/JC5/firefly-iii/files/610003/firefly-rabobank.txt)
- When I say I start the import proces, I select both files, and comma as separator and click next>next>finish.

The first time, the import goes well. Then I click on the newly created tag and see the imported transactions.
I delete all transactions in this screen (just because I can), and run the import again.
Now I get this error:
![image](https://cloud.githubusercontent.com/assets/441924/20578695/d1e175ce-b1c8-11e6-87fd-2c1857246e5f.png)

But, it is not really a timeout: Firefly encounters an error:
Line 120 of ImportStorage.php:

> [2016-11-23 21:00:45] testing.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Trying to get property of non-object","time":"Wed, 23 Nov 2016 21:00:45 +0000","file":"\/var\/w$
[2016-11-23 21:00:46] testing.ERROR: ErrorException: Trying to get property of non-object in /var/www/sub.domain.com/public_html/app/Import/ImportStorage.php:120
Stack trace:
#0 /var/www/sub.domain.com/public_html/app/Import/ImportStorage.php(120): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/test-f...', 1$
#1 /var/www/sub.domain.com/public_html/app/Import/ImportStorage.php(349): FireflyIII\Import\ImportStorage->alreadyImported('529ff3ded57efa0...')
#2 /var/www/sub.domain.com/public_html/app/Import/ImportStorage.php(94): FireflyIII\Import\ImportStorage->storeSingle(1, Object(FireflyIII\Import\ImportEntry))
#3 /var/www/sub.domain.com/public_html/app/Import/ImportProcedure.php(72): FireflyIII\Import\ImportStorage->store()
#4 /var/www/sub.domain.com/public_html/app/Http/Controllers/ImportController.php(321): FireflyIII\Import\ImportProcedure::runImport(Object(FireflyIII\Models\ImportJob))
#5 [internal function]: FireflyIII\Http\Controllers\ImportController->start(Object(FireflyIII\Models\ImportJob))
#6 /var/www/sub.domain.com/public_html/bootstrap/cache/compiled.php(9389): call_user_func_array(Array, Array)
#7 /var/www/sub.domain.com/public_html/bootstrap/cache/compiled.php(9416): Illuminate\Routing\Controller->callAction('start', Array)
#8 /var/www/sub.domain.com/public_html/bootstrap/cache/compiled.php(8474): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Co$
#9 /var/www/sub.domain.com/public_html/bootstrap/cache/compiled.php(8455): Illuminate\Routing\Route->runController()
#10 /var/www/sub.domain.com/public_html/bootstrap/cache/compiled.php(8151): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /var/www/sub.domain.com/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http$
#12 /var/www/sub.domain.com/public_html/app/Http/Controllers/ImportController.php(50): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

So I would expect the import to work the second time as well, and expect it to show the real error instead of the timeout.

When I restart the import without deleting the records, everything goes fine. It tells me that the records already exist.

**Comment by JC5** [comment]
I know what would cause that. It's a sloppy delete routing, possibly with a
missing foreign key. I'll look into it!

**Comment by zjean** [comment]
Great. To add on the timeout-stuff: I did an import yesterday (on develop) with an import file that contained wrong IBAN's, In the log I saw the error about the IBAN not being valid. The UI only showed me the error like in the screenshot. I don't know if you have in mind to improve that as well?

**Comment by JC5** [comment]
Yes, a bad IBAN should be displayed. However, I was under the impression
that firefly-iii could reasonably handle that (without timing out). I'll
look into it.

**Comment by JC5** [comment]
Firefly should be able to import a file with wrong IBAN's. The error logging warns you but it doesn't really respond: it just shows an error and moves on. This is more or less by design. The idea is not to fail the import.

The bug with the ImportStorage is fixed. The IBAN thing will have to wait for a rewrite of the import routine.
