### ISSUE TITLE
Seperate Category when having whitespace an the end

### ISSUE THREAD

**Issue by schwalberich** [JC5/firefly-iii#419]
Hello, 
i recently had  a small issue when  looking at the category summary.
When adding a New transaction with the category "food " although "food" is already available (thanks to autocorrect)
It created a complete New category .

I think this could be fixed by a simple trim function  if wanted.

Best regards

**Comment by JC5** [comment]
I thought there was one already. I'll search the code for this and fix it
if necessary. Thanks for reporting this!
