### ISSUE TITLE
Password strength indicator

### ISSUE THREAD

**Issue by ximex** [JC5/firefly-iii#421]
Use a password strength indicator like https://github.com/dropbox/zxcvbn

**Comment by JC5** [comment]
That's what password managers are for.

**Comment by ximex** [comment]
The use of a password manager isn't a guaranty that the users use good passwords ;-)

**Comment by JC5** [comment]
True! 😁 

But honestly, I don't really care what passwords people use. It's their own installation, their own data on their own server. If they manage to install Firefly, which isn't that easy and still use `qwerty` as their password it's their own damn fault.
