### ISSUE TITLE
[category report] Income and expenses shows incorrect amount

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#422]
When you select multiple years (eg; 2015-2016) the first diagram 'Income and expenses' shows the wrong amount. It looks like it divides the 'expenses' on all the years?

And the pie dagram 'Income per account' is not readable when the income is on the right side of the chart.

**Comment by JC5** [comment]
There are some conditions where the label could expand beyond the box the chart is in. That's not something I can help, unfortunately. 

As for the expenses, I'll check it out. Will need to generate some test data.

**Comment by JC5** [comment]
Found and fixed. Could you confirm?
