### ISSUE TITLE
New tag in transaction screen not saved

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#427]
Should a not existing tag be stored as a new tag and be linked to the transaction? I would expect so, but it doesn't work (anymore?).

I enter the tag in the transaction screen like this (it doesn't get the tag-styling as well) and it isn't stored.
![screen shot 2016-11-25 at 21 15 22](https://cloud.githubusercontent.com/assets/441924/20634753/836711aa-b354-11e6-89ad-957df3e56d36.png)

**Comment by JC5** [comment]
If the tag does not register as a tag when you press enter, you might need to do a hard refresh.

**Comment by JC5** [comment]
I'm actually really glad that was the problem. You got me worried there ;).

**Comment by zjean** [comment]
I still have a question. I have a balancing tag, called 'Advance'.
I try to create a transaction and add the tag to it. When I type into the field, the autocomplete shows 'Advance' and is selected. I press enter to confirm that. The tag field also shows sth like 'advance' behind the tag:
![screen shot 2016-11-25 at 23 32 17](https://cloud.githubusercontent.com/assets/441924/20636142/bdd7f558-b367-11e6-88ac-888ae025fd10.png)

When I save the transaction, and open it, I don't see a tag defined. When I go to the details of the tag, the transaction is not listed.
![screen shot 2016-11-25 at 23 32 49](https://cloud.githubusercontent.com/assets/441924/20636146/d3d55f58-b367-11e6-8271-b2740f1481e8.png)
I am on Chrome on Mac OS Sierra, tried Safari as well. I don't get console errors and did a hard refresh as well. Any ideas?

**Comment by JC5** [comment]
Check if your log files mention why the tag was not saved. There are some situations where the tag cannot be added to the journal. For example, adding two withdrawals to the same advance payment tag.

Although Firefly does not give any feedback, the tag is not saved. This should be updated. The log files however tell you what has happened.

**Comment by zjean** [comment]
I ran the upgrade procedure (as described [here] (https://firefly-iii.github.io/upgrade-guide/) again and now everything is fine. Can you expand the alternative way with --no-dev on the composer commands?

**Comment by JC5** [comment]
Done!
