### ISSUE TITLE
Change monthly Overview on mobile devices

### ISSUE THREAD

**Issue by schwalberich** [JC5/firefly-iii#435]
Hello again :)

I don't know if it is possible or I Just didn't find the point on the mobile-device site.

On Desktop PCs I am able to change the month of the overview:
![firefly](https://cloud.githubusercontent.com/assets/23633186/20708090/a508c5b0-b62e-11e6-85fb-fc2e7a27e62c.PNG)

Is this also possible on mobile-devices?

Best Regards

**Comment by JC5** [comment]
It should be. I'll turn it on, and try it a few times. If it really does not fit or doesn't work properly, I can build a dedicated page. It'll be a tad slower, but workable.

**Comment by JC5** [comment]
It works pretty well. I think the next release will have this.
