### ISSUE TITLE
"Whoops, something went wrong" When adding transaction

### ISSUE THREAD

**Issue by dfiel** [JC5/firefly-iii#437]
When I try to create a new transaction, I get an Error 500, and refreshing the page gives the standard "Whoops, something went wrong". I am unfamiliar where the error logs are saved.

I'm running this on an Ubuntu 16.04 server, latest version of Firefly.

Thanks,

     dfiel

**Comment by JC5** [comment]
The log files should be in `storage/logs`. Otherwise, I can't tell you anything but "yes, something went wrong when creating a transaction".

If you open the ``.env`` file, you can set `APP_DEBUG` to `true` so the error messages will contain more debug information for me to analyse.

**Comment by JC5** [comment]
Any news?

**Comment by dfiel** [comment]
Sorry, I completely forgot I opened this issue. I've been having a tough week with school, I should have time to update after 3PM today.

**Comment by JC5** [comment]
No problem, take your time to find the issue! I'll be right here :-)

**Comment by dfiel** [comment]
Alright, looks like in COnnection.php line 761, Field 'order' doesn't have a default value. I uploaded the entire error page to Pastebin [here](http://pastebin.com/VnZS6zK4).

**Comment by JC5** [comment]
The `order` field should have a default value. It is defined [here](https://github.com/JC5/firefly-iii/blob/master/database/migrations/2016_06_16_000002_create_main_tables.php#L529).

However if this is broken because of some reason, you can fix this yourself. Looking at the queries, are you using MySQL or Sqlite?

In either case, a program such as phpMyAdmin or "DB Browser for SQLite" can help you to change the table `transaction_journals`. In this table there is a column `order` which you should give the default value of `0`.

Let me know if this works!

**Comment by dfiel** [comment]
I'm using mySQL. Let me try this and get back to you

**Comment by dfiel** [comment]
Sorry, I completely forgot I opened this issue.

I changed the default calue of order, and now I'm getting a different error.

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'description' cannot be null (SQL: insert into `transactions` (`transaction_journal_id`, `account_id`, `amount`, `description`, `identifier`, `updated_at`, `created_at`) values (91, 1, -14, , 0, 2016-12-14 21:08:09, 2016-12-14 21:08:09))

**Comment by JC5** [comment]
Alright, that's very strange because that field too has long been fixed. I remember there was an issue about it.

But to save your database so far we'll just have to update fields until they work! =)

Open your database, find table `transactions` and click `nullable` in the field list.

**Comment by dfiel** [comment]
I'm using MySQL Workbench to do the work, and this is what I see:

![image](https://cloud.githubusercontent.com/assets/7292540/21244779/23d3b2ae-c2ed-11e6-8d5e-7e94f0e8a4cb.png)

I changed description to "Not Null", and I still get the error.

**Comment by JC5** [comment]
That's another table ;). Find table "transactions", and put NULL in the default/expression column.

**Comment by dfiel** [comment]
Aha, that worked! I'm going to start putting my transactions in and see if any more errors arise.
