### ISSUE TITLE
Support for Bigger Transaction Values

### ISSUE THREAD

**Issue by kerti** [JC5/firefly-iii#439]
Hi James,

Firefly is great, I've been playing around with it for a while and it seems to suit my needs. However, I'm using Indonesian Rupiah (IDR), and because of the conversion rate (USD 1 = 13000-ish IDR), the current format of `decimal(10, 4)` for transactions and balances would not suffice. I think `decimal(14, 4)` would be sufficient as it would be capable of representing values up to 1 billion IDR (about 75k USD).

I think I can get away with editing the seed file myself (please CMIIW), but I wonder if you have any plans to support larger transaction values.

**UPDATE**: I edited the seed files and re-seeded the app database. Unfortunately for me I've previously created a new currency (IDR, Indonesian Rupiah) and set it as default. The app crashed until I manually created the IDR currency using mysql client. I tried looking into redis to see if anything was cached, but I couldn't find anything there.

**Comment by JC5** [comment]
Hi kerti,

Thank you for the compliments! :-)

I've updated the migration files. You can check [this commit](https://github.com/JC5/firefly-iii/commit/86ea9db37ed4d19201ded8743ea6c258e4928beb) to see which lines need to be updated, until a new release is ready.

The currency preference is cached and can survive a re-seed of the database. To make sure the cache is clear, run the command `php artisan cache:clear`.

**Comment by kerti** [comment]
Thanks James, that was quick, and my installation is now up and running. :+1:

**Comment by JC5** [comment]
Cool!
