### ISSUE TITLE
Editing an account sets virtual balance field to 0.000

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#479]
When I try to save the account, it tells me that the value of the virtual balance must be greater than 0.000. I don't want to do anything with the virtual balance (just setting the initial balance in this case) but it got filled by firefly and I need to erase it manually.

**Comment by JC5** [comment]
That seems to be a bug! I'll look into it tonight.

**Comment by JC5** [comment]
I introduced a bug last version. Nice catch.

**Comment by zjean** [comment]
Nice, fixed!
