### ISSUE TITLE
Importer stores description too

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#483]
It looks like the importer stores the description of an imported transaction at the transaction and the transaction journal. That seems to have the result that the description of a transaction is displayed twice which clutters the views.

See below screenshot: the first transaction is entered manually, the second is created by the importer.
![image](https://cloud.githubusercontent.com/assets/441924/21361834/137dbba0-c6e6-11e6-8beb-864981c9acbd.png)

It looks to me as if this could be fixed easily [here](https://github.com/JC5/firefly-iii/blob/master/app/Import/ImportStorage.php#L379) and  [here](https://github.com/JC5/firefly-iii/blob/master/app/Import/ImportStorage.php#L386)

**Comment by zjean** [comment]
Besides the above I see that the description in the journal is encrypted while the description in the transaction itself isn't. Is the latter intended?

**Comment by JC5** [comment]
That's easy to fix indeed, thanks for pointing me in the right direction!

I'm slowly moving away from local encryption. It makes it impossible to search in data and doesn't do much, security wise.

**Comment by JC5** [comment]
Cleaning up, closing issues. Let me know if you need anything else regarding this!
