### ISSUE TITLE
Importer mapping view shows initial balance accounts

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#487]
Hi,
when defining the import settings during the import, one of the steps is to map IBAN's to accounts known by Firefly.
This list shows not only 'normal' accounts but also initial balance accounts. Is this intended / useful behaviour? It clutters the list ;-)

See my (not so clear anonymized) example below:
![image](https://cloud.githubusercontent.com/assets/441924/21399517/4a92afda-c7ac-11e6-8539-053ad5764685.png)

**Comment by JC5** [comment]
They shouldn't be mentioned, [they're being filtered out](https://github.com/JC5/firefly-iii/blob/master/app/Import/Mapper/OpposingAccounts.php#L35). 

Are those initial balance accounts actually initial balance accounts?

**Comment by zjean** [comment]
No, they are of type Revenue Account. I just did an import of quite a lot of data, and I expect that the importer created them.

**Comment by JC5** [comment]
Wow, you're finding quite the obscure bugs today. Nice work :D.

Those accounts should have been initial balance accounts which would have hidden them. FF never made them as initial balance accounts though. Hence the problem.

It should be fixed in a few minutes.

**Comment by zjean** [comment]
Okay, maybe you find the root cause already, but I think the bug is not (that much) import related. I can reproduce it easily on master, by renaming a Revenue account. It creates the initial balance account as Revenue account as well and shows up in the Debtors-list

**Comment by JC5** [comment]
You're absolutely right, it wasn't import related. Turns out the "create new account"-routine does not store the initial balance in an "initial balance account" but in a revenue/expense account.

**Comment by JC5** [comment]
I'm closing this, just to clean up. Let me know if you run into any issues :).
