### ISSUE TITLE
Strange behaviour during moving transaction to another destination account in a rule

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#488]
Hi,
I created a rule to move transactions from Rabo Omnikassa to a Generic creditor.
I run this rule with the execute button at the rule group, because the transaction already exists.
When the execution is ready, the transaction is at the Generic creditor, but when I open it, it shows the old creditor still at the header. The line shows the correct creditor.

![image](https://cloud.githubusercontent.com/assets/441924/21406896/1c4391ea-c7ce-11e6-96a1-7dbce999afbf.png)

Could this be a weird caching problem? (I ran php artisan cache:clear, and views:clear already and logged in again). Or is the journal header not updated correctly?

**Comment by JC5** [comment]
Mmmm. I'm checking the code as we speak but I can't find many weird things. You can see what the database had to say about this transaction (journal).

- The journal itself (see the URL for the ID) is stored in table `transaction_journals`.
- There should be two transactions stored for a journal. You can find them in the table `transactions` when you filter using `transaction_journal_id` (guess which ID you'll need).

It could be that there are more than two transactions in the table. There should at least be two where the `deleted_at` column is blank.

Each transaction in the `transactions` table has a column `account_id`. Find these accounts in the table `accounts` and check if they match the "Transactieinformatie" accounts or if they match the "Transacties" accounts. This will point me in the right direction.

**Comment by JC5** [comment]
My own attempts to recreate this can't seem to get this to "not work". Both accounts are updated.

**Comment by zjean** [comment]
Thanks for your response, I will try to have a look tonight ;-)

**Comment by zjean** [comment]
I can't reproduce it anymore.
There are only two transactions, both linking to the correct accounts.
