### ISSUE TITLE
Custom range budget availability

### ISSUE THREAD

**Issue by Zeami** [JC5/firefly-iii#489]
Hi,

If I've chosen a custom date range (for example between December 20, 2016 and January 24, 2017) and tried to set up my budget for this range, I can't set the available budget amount between this range. 

![customrange](https://cloud.githubusercontent.com/assets/24712549/21419300/193600b0-c827-11e6-8fb1-2a4bc560e6fe.png)

There's always the default amount of "1000.00" and if I click on the amount to change it, It shows me the range of the current month even though I've specified the range.

![amount](https://cloud.githubusercontent.com/assets/24712549/21419310/2526ef24-c827-11e6-9cef-1200cbeb9485.png)

Thanks!

**Comment by JC5** [comment]
Yes. I built it for me, and I budget per month :P. But you're right, it should be a more flexible setting.

**Comment by JC5** [comment]
The next version of Firefly will feature this! :D
