### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by skibbipl** [JC5/firefly-iii#490]
Does firefly 4.2.2 supports multiple users? I can't see any option to create a new account after initial registering.

**Comment by JC5** [comment]
It does, but not by default. Checkout the `/admin/configuration` page.

**Comment by jleeong** [comment]
@JC5 I'm currently using v 4.6.4 and navigating to `my_firefly_url/admin/configuration` just redirects to the home page. Is there any other documentation for the related configuration settings?
