### ISSUE TITLE
Suggestion: localizations

### ISSUE THREAD

**Issue by sion2k** [JC5/firefly-iii#498]
Hi,

Firefly III is pretty cool tool but is there any way for adding new localizations. I thought about working on Russian one and I can take care of this but some entry point is needed. Is there any way to do this and, if yes, how can I start with this?

**Comment by JC5** [comment]
Hi!

You can join [CrowdIn](https://crowdin.com/project/firefly-iii) where I have just enabled Russian. The next version of Firefly will then include it as an option!

**Comment by sion2k** [comment]
Cool, thanks! Joined and started translation.
