### ISSUE TITLE
Links in meta-information box of transaction link to accounts

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#501]
The links (Category / Budget) in the meta-information box in the details of a transaction link to an accounts page, instead of the respective category/budget pages.
![image](https://cloud.githubusercontent.com/assets/441924/21508488/c13fda16-cc81-11e6-8892-56a4d8278254.png)

Affected lines:
https://github.com/JC5/firefly-iii/blob/ad1e9c27e956705d30283fbae70115b076e23c9f/app/Support/Twig/Journal.php#L256
https://github.com/JC5/firefly-iii/blob/ad1e9c27e956705d30283fbae70115b076e23c9f/app/Support/Twig/Journal.php#L261
https://github.com/JC5/firefly-iii/blob/ad1e9c27e956705d30283fbae70115b076e23c9f/app/Support/Twig/Journal.php#L291
https://github.com/JC5/firefly-iii/blob/ad1e9c27e956705d30283fbae70115b076e23c9f/app/Support/Twig/Journal.php#L302

**Comment by JC5** [comment]
Nice find! It'll be fixed in the next release.
