### ISSUE TITLE
Always show number of transactions and link to details in report item

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#502]
Hi,
currently the financial report only shows the number of transactions and the (i)nfo button only when there are more then 1 transaction.
![image](https://cloud.githubusercontent.com/assets/441924/21508756/e4326136-cc83-11e6-8885-405d4d25f74d.png)

I would like it to always show the info button, to have an easy way to show the details of the transaction without having to leave the page or opening a new tab and having to click 'ungroup' transactions to show the details.
It looks like it is easy to implement, but maybe there is a solid reason for the current behaviour?

**Comment by JC5** [comment]
That should not be hard, I'll experiment with the placement :)

**Comment by JC5** [comment]
You can see the result at the [demo site](https://firefly-iii.nder.be/). Login, go to reports and check out the default report.

**Comment by zjean** [comment]
Nice job, thanks!
