### ISSUE TITLE
More decimal places

### ISSUE THREAD

**Issue by xpfgsyb** [JC5/firefly-iii#506]
Hi, can we get more decimal places please?

Background story: I am used to track my Bitcoin transactions in the current software and would like to do the same in Firefly. Unfortunately Firefly seems to round to two decimals, but Bitcoin (like most of the digital currencies) has 8 decimal places after the comma. It would be great if it would be possible to configure the decimals per currency, so that the rounding does work right and the correct amount of decimals is shown in Firefly.

**Comment by JC5** [comment]
It's possible!

It has quite some impact and it won't be the next version. But absolutely.

**Comment by xpfgsyb** [comment]
Wow, I'm impressed about your speed. Thank you for your great work!
...I had to Google that one thing too when I changed it in my current system :)

**Comment by JC5** [comment]
Alright most of the code should be able to handle this now. That went better than expected! Expect the next release of Firefly to support this.
