### ISSUE TITLE
Install not work

### ISSUE THREAD

**Issue by polcape** [JC5/firefly-iii#56]
I have follow the wiki for installation of firefly III but not working.
After registration and login with the send password I obtain this message:
"Whoops, looks like something went wrong"

**Comment by JC5** [comment]
Please check the directory ``app/storage/logs`` and see if the log files have something to say when you try to register. At the moment, Firefly does not really catch errors when registering, it just says "it went wrong".

Let me know what the logs tell you, and I'll be able to help you!

**Comment by polcape** [comment]
I have found this issue https://github.com/JC5/firefly-iii/issues/54 and I have follow the istruction at this link and now all work.
In particular I have moved the doctrine/dbal to require section in composer.json and I have use the SQL file indicated in the topic to populate the DB.

**Comment by JC5** [comment]
Thanks! I see I completely forgot to update composer.json for this problem. I will push a new release tonight.
