### ISSUE TITLE
Initial add account problem

### ISSUE THREAD

**Issue by polcape** [JC5/firefly-iii#57]
I have install the app (https://github.com/JC5/firefly-iii/issues/56) using the istruction here https://github.com/JC5/firefly-iii/issues/54 with the database indicated but when I try to click "Start from Scratch" to add new account, I filled every field (also opening amount) I get an error.

Then if I go to account I see the added account but the balance is 0 and if I try to set opening ablance again the value still remain at 0.

This is the log after the error of adding account:

[2015-01-13 18:07:42] production.ERROR: 500: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-11-BPER' for key 'accounts_user_id_account_type_id_name_unique'' in /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ac...', Array)
#2 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#3 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#4 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#5 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#6 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(935): call_user_func_array(Array, Array)
#9 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/servizi/firefly/bootstrap/compiled.php(6890): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/servizi/firefly/bootstrap/compiled.php(6847): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/servizi/firefly/app/lib/FireflyIII/Database/Account/Account.php(320): Illuminate\Database\Eloquent\Model->save()
#14 /var/www/html/servizi/firefly/app/controllers/AccountController.php(191): FireflyIII\Database\Account\Account->store(Array)
#15 [internal function]: AccountController->store()
#16 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#17 /var/www/html/servizi/firefly/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('store', Array)
#18 /var/www/html/servizi/firefly/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(AccountController), Object(Illuminate\Routing\Route), 'store')
#19 /var/www/html/servizi/firefly/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AccountControll...', 'store')
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /var/www/html/servizi/firefly/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#22 /var/www/html/servizi/firefly/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 /var/www/html/servizi/firefly/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /var/www/html/servizi/firefly/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/servizi/firefly/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#26 /var/www/html/servizi/firefly/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/servizi/firefly/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/servizi/firefly/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/servizi/firefly/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#30 /var/www/html/servizi/firefly/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#31 /var/www/html/servizi/firefly/public/index.php(59): Illuminate\Foundation\Application->run()
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-11-BPER' for key 'accounts_user_id_account_type_id_name_unique' (SQL: insert into `accounts` (`name`, `active`, `user_id`, `account_type_id`, `updated_at`, `created_at`) values (BPER, 1, 1, 11, 2015-01-13 18:07:42, 2015-01-13 18:07:42))' in /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#1 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#2 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#3 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#4 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(935): call_user_func_array(Array, Array)
#7 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/servizi/firefly/bootstrap/compiled.php(6890): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/servizi/firefly/bootstrap/compiled.php(6847): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/servizi/firefly/app/lib/FireflyIII/Database/Account/Account.php(320): Illuminate\Database\Eloquent\Model->save()
#12 /var/www/html/servizi/firefly/app/controllers/AccountController.php(191): FireflyIII\Database\Account\Account->store(Array)
#13 [internal function]: AccountController->store()
#14 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#15 /var/www/html/servizi/firefly/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('store', Array)
#16 /var/www/html/servizi/firefly/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(AccountController), Object(Illuminate\Routing\Route), 'store')
#17 /var/www/html/servizi/firefly/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AccountControll...', 'store')
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 /var/www/html/servizi/firefly/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#20 /var/www/html/servizi/firefly/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 /var/www/html/servizi/firefly/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /var/www/html/servizi/firefly/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/servizi/firefly/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/servizi/firefly/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/servizi/firefly/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/servizi/firefly/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/servizi/firefly/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/servizi/firefly/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#29 /var/www/html/servizi/firefly/public/index.php(59): Illuminate\Foundation\Application->run()
#30 {main} [] []

**Comment by JC5** [comment]
Yay, that's quite a bug! I've fixed it in 3.2.4

You might run into bugs like these more often. At the moment I'm transitioning to a new way of validating user content, anticipating some big changing in user data validation.

**Comment by polcape** [comment]
Ok, thanks. I have made git pull and if I add new account with a new name no error are show and also work the amount feature.
If I try to insert the name of account that I used before this error is given, so I have remove all references of this old name from DB and retry and now works.

[2015-01-13 22:25:34] production.ERROR: 500: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-11-BPER' for key 'accounts_user_id_account_type_id_name_unique'' in /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ac...', Array)
#2 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#3 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#4 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#5 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#6 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(935): call_user_func_array(Array, Array)
#9 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /var/www/html/servizi/firefly/bootstrap/compiled.php(6890): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /var/www/html/servizi/firefly/bootstrap/compiled.php(6847): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /var/www/html/servizi/firefly/app/lib/FireflyIII/Database/Account/Account.php(341): Illuminate\Database\Eloquent\Model->save()
#14 /var/www/html/servizi/firefly/app/controllers/AccountController.php(191): FireflyIII\Database\Account\Account->store(Array)
#15 [internal function]: AccountController->store()
#16 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#17 /var/www/html/servizi/firefly/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('store', Array)
#18 /var/www/html/servizi/firefly/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(AccountController), Object(Illuminate\Routing\Route), 'store')
#19 /var/www/html/servizi/firefly/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AccountControll...', 'store')
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /var/www/html/servizi/firefly/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#22 /var/www/html/servizi/firefly/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 /var/www/html/servizi/firefly/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /var/www/html/servizi/firefly/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /var/www/html/servizi/firefly/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#26 /var/www/html/servizi/firefly/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/servizi/firefly/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/servizi/firefly/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/servizi/firefly/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#30 /var/www/html/servizi/firefly/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#31 /var/www/html/servizi/firefly/public/index.php(59): Illuminate\Foundation\Application->run()
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-11-BPER' for key 'accounts_user_id_account_type_id_name_unique' (SQL: insert into `accounts` (`name`, `active`, `user_id`, `account_type_id`, `updated_at`, `created_at`) values (BPER, 1, 1, 11, 2015-01-13 22:25:34, 2015-01-13 22:25:34))' in /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#1 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#2 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#3 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#4 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(935): call_user_func_array(Array, Array)
#7 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/servizi/firefly/bootstrap/compiled.php(6900): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/servizi/firefly/bootstrap/compiled.php(6890): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/servizi/firefly/bootstrap/compiled.php(6847): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/servizi/firefly/app/lib/FireflyIII/Database/Account/Account.php(341): Illuminate\Database\Eloquent\Model->save()
#12 /var/www/html/servizi/firefly/app/controllers/AccountController.php(191): FireflyIII\Database\Account\Account->store(Array)
#13 [internal function]: AccountController->store()
#14 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#15 /var/www/html/servizi/firefly/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('store', Array)
#16 /var/www/html/servizi/firefly/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(AccountController), Object(Illuminate\Routing\Route), 'store')
#17 /var/www/html/servizi/firefly/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AccountControll...', 'store')
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 /var/www/html/servizi/firefly/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#20 /var/www/html/servizi/firefly/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 /var/www/html/servizi/firefly/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /var/www/html/servizi/firefly/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/servizi/firefly/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/servizi/firefly/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/servizi/firefly/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/servizi/firefly/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/servizi/firefly/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/servizi/firefly/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#29 /var/www/html/servizi/firefly/public/index.php(59): Illuminate\Foundation\Application->run()
#30 {main} [] []
[2015-01-13 22:27:03] production.ERROR: 500: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-11-BPER' for key 'accounts_user_id_account_type_id_name_unique'' in /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php:391
Stack trace:
#0 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(391): PDOStatement->execute(Array)
#1 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `account...', Array)
#2 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('update `account...', Array, Object(Closure))
#3 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\Database\Connection->run('update `account...', Array, Object(Closure))
#4 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\Database\Connection->affectingStatement('update `account...', Array)
#5 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1911): Illuminate\Database\Connection->update('update `account...', Array)
#6 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(316): Illuminate\Database\Query\Builder->update(Array)
#7 /var/www/html/servizi/firefly/bootstrap/compiled.php(6874): Illuminate\Database\Eloquent\Builder->update(Array)
#8 /var/www/html/servizi/firefly/bootstrap/compiled.php(6845): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /var/www/html/servizi/firefly/app/lib/FireflyIII/Database/Account/Account.php(380): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/html/servizi/firefly/app/controllers/AccountController.php(229): FireflyIII\Database\Account\Account->update(Object(Account), Array)
#11 [internal function]: AccountController->update(Object(Account))
#12 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#13 /var/www/html/servizi/firefly/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('update', Array)
#14 /var/www/html/servizi/firefly/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(AccountController), Object(Illuminate\Routing\Route), 'update')
#15 /var/www/html/servizi/firefly/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AccountControll...', 'update')
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Account))
#17 /var/www/html/servizi/firefly/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#18 /var/www/html/servizi/firefly/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 /var/www/html/servizi/firefly/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 /var/www/html/servizi/firefly/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /var/www/html/servizi/firefly/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/servizi/firefly/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/html/servizi/firefly/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/servizi/firefly/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/servizi/firefly/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/servizi/firefly/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#27 /var/www/html/servizi/firefly/public/index.php(59): Illuminate\Foundation\Application->run()
#28 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-11-BPER' for key 'accounts_user_id_account_type_id_name_unique' (SQL: update `accounts` set `updated_at` = 2015-01-13 22:27:03, `name` = BPER where `id` = 6)' in /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('update `account...', Array, Object(Closure))
#1 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\Database\Connection->run('update `account...', Array, Object(Closure))
#2 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\Database\Connection->affectingStatement('update `account...', Array)
#3 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1911): Illuminate\Database\Connection->update('update `account...', Array)
#4 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(316): Illuminate\Database\Query\Builder->update(Array)
#5 /var/www/html/servizi/firefly/bootstrap/compiled.php(6874): Illuminate\Database\Eloquent\Builder->update(Array)
#6 /var/www/html/servizi/firefly/bootstrap/compiled.php(6845): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 /var/www/html/servizi/firefly/app/lib/FireflyIII/Database/Account/Account.php(380): Illuminate\Database\Eloquent\Model->save()
#8 /var/www/html/servizi/firefly/app/controllers/AccountController.php(229): FireflyIII\Database\Account\Account->update(Object(Account), Array)
#9 [internal function]: AccountController->update(Object(Account))
#10 /var/www/html/servizi/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#11 /var/www/html/servizi/firefly/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('update', Array)
#12 /var/www/html/servizi/firefly/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(AccountController), Object(Illuminate\Routing\Route), 'update')
#13 /var/www/html/servizi/firefly/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AccountControll...', 'update')
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Account))
#15 /var/www/html/servizi/firefly/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#16 /var/www/html/servizi/firefly/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 /var/www/html/servizi/firefly/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 /var/www/html/servizi/firefly/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/html/servizi/firefly/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/html/servizi/firefly/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/html/servizi/firefly/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/html/servizi/firefly/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/html/servizi/firefly/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/servizi/firefly/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#25 /var/www/html/servizi/firefly/public/index.php(59): Illuminate\Foundation\Application->run()
#26 {main} [] []
