### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by thedd** [JC5/firefly-iii#73]
I'd really like to try your application but it seems to be impossible to install.
The installation instructions in the wiki is also out of date.
Currently I'm getting the following error:
> Fatal error: Class 'Symfony\Component\Finder\Adapter\AbstractAdapter' not found in .../firefly-iii/vendor/symfony/finder/Symfony/Component/Finder/Adapter/AbstractFindAdapter.php on line 28

I installed composer and tried to install with
> composer update --prefer-dist --no-dev

and 

> composer update --prefer-dist

Can someone please help me with that? Thanks!

**Comment by JC5** [comment]
I've updated the wiki and found the first bug. Will keep you posted.

**Comment by JC5** [comment]
I've pushed version 3.3.8 which should fix the problem!

**Comment by thedd** [comment]
Thanks!
Now I'm getting further, but I'm not quite there.

I'm not presented with the following error:

> The requested URL /subfolder/firefly-iii/public/auth/login was not found on this server.

I installed it in a subfolder, not the webroot. Either that's wrong or it's something with the mod-rewrite/htaccess. But i can't figure it out.

**Comment by JC5** [comment]
Hi! Which server are you using? Is it apache, or something else? I've managed to get it working fairly easily.

Here's the routine I've used:

```
vagrant@host:~$ cd /vagrant_data/Sites/test-root/
vagrant@host:/vagrant_data/Sites/test-root$ pwd
/vagrant_data/Sites/test-root
vagrant@host:/vagrant_data/Sites/test-root$ cd subdir/
vagrant@host:/vagrant_data/Sites/test-root/subdir$ git clone https://github.com/JC5/firefly-iii.git
Cloning into 'firefly-iii'...
vagrant@host:/vagrant_data/Sites/test-root/subdir$ cd firefly-iii/
vagrant@host:/vagrant_data/Sites/test-root/subdir/firefly-iii$ cp .env.example .env
vagrant@host:/vagrant_data/Sites/test-root/subdir/firefly-iii$ nano .env
vagrant@host:/vagrant_data/Sites/test-root/subdir/firefly-iii$ chmod -R 777 storage/
vagrant@host:/vagrant_data/Sites/test-root/subdir/firefly-iii$ composer update --prefer-dist --no-dev
Loading composer repositories with package information
vagrant@host:/vagrant_data/Sites/test-root/subdir/firefly-iii$
```

If it's not working on Apache, I will expand the installation guides to include something I forgot to ask:

* Is your webserver setup to allow ``.htaccess`` files to overrule configuration?


![screen shot 2015-04-21 at 16 37 21](https://cloud.githubusercontent.com/assets/5889984/7254655/c8d0cd4e-e844-11e4-8cb2-17c5cf951af5.png)

**Comment by thedd** [comment]
Yes, I'm using Apache.
> Is your webserver setup to allow .htaccess files to overrule configuration?
I think this might be the problem.

**Comment by JC5** [comment]
Yes, there is!

[Here](https://geld.nder.be/) is a demo site, and [here](https://github.com/JC5/firefly-iii/wiki/Privacy-on-demo-site) is what you need to know before you use it.
