### ISSUE TITLE
Piggy banks - duplicate button

### ISSUE THREAD

**Issue by edupacios** [JC5/firefly-iii#74]
On piggy banks index view, when there are no piggy banks set up, there are two "create piggy bank" buttons, one above the other. Maybe the intention was to show one button at the top of the page and the other below the "account status" table.
When having 2 or 3 piggy banks, the two buttons are still close. It could make sense if you have 20 piggy banks set up, show a top button and a bottom one.
Sorry if I misunderstood your idea!

**Comment by JC5** [comment]
You're absolutely right!

The button used to be useful when you had a lot of piggy banks but with the current table view, it's not that necessary to have. I've removed it. Thanks for pointing it out :)
