### ISSUE TITLE
Unclosed "(" in "auth.log" => twig exception after clean install

### ISSUE THREAD

**Issue by RonaldvanMeer** [JC5/firefly-iii#88]
Dear fellow programmers,

i've clean installed FireFly and found a bug.
Recently you've updated the login part by using URL.to #86 functionality.

sadly a (breaking) bug prohibits the render of the login & register screen. (i haven't gone further) perhaps you could check the following + the changes done on other code?

path: firefly-iii/resoureces/twig/auth/
files:
login.twig => line 21,  char 46 should be a ")"-sign. Link (https://github.com/JC5/firefly-iii/blame/master/resources/twig/auth/login.twig#L21)
                => line 48, char 45 should be a ")"-sign. Link (https://github.com/JC5/firefly-iii/blame/master/resources/twig/auth/login.twig#L48)

register.twig => line 21, char 89 should be a ")"-sign. Link (https://github.com/JC5/firefly-iii/blame/master/resources/twig/auth/register.twig#L21)
                    => line 41, char 41 should be a ")"-sign. Link (https://github.com/JC5/firefly-iii/blame/master/resources/twig/auth/register.twig#L41)
                    => line 42, char 45 should be a ")"-sign. Link (https://github.com/JC5/firefly-iii/blame/master/resources/twig/auth/register.twig#L42)

kind regards,
Ronald van Meer

**Comment by JC5** [comment]
Hi Ronald,

Thanks! I've created and released a new version to address this bug. I had no idea that it existed. Version 3.4.8 should be live soon and you should be able to update fairly easily.

When you are completely sure your fix will work, and it will solve the problem, you could also create [a pull request](https://help.github.com/articles/using-pull-requests/). It's a pretty nifty feature!

Regards,

Sander
