### ISSUE TITLE
Changlelog

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#89]
Do you have a changelog?

**Comment by JC5** [comment]
Nope!

It is on my eternal to do list to actually write a changelog whenever I release a new [version](https://github.com/JC5/firefly-iii/releases). So far, I haven't been able to, because I am lazy.

The first changelog I'll write will probably include your excellent idea from the other thread :)

**Comment by JC5** [comment]
See

https://github.com/JC5/firefly-iii/releases/tag/3.4.10
