### ISSUE TITLE
After clean install, new user creation fails

### ISSUE THREAD

**Issue by RonaldvanMeer** [JC5/firefly-iii#91]
Hello,

I've clean installed firefly-iii and got past the login screen.
I end up here: http://192.168.1.103/new-user (don't mind the domain).
I fill out "Bankname, Balance, savings balance, credit card limit", and submit the data.
I get routed to http://192.168.1.103/new-user/submit, which seems logical. but The page shows "Whoops, looks like something went wrong". in the debug log i found this : 
production.ERROR: exception 'ErrorException' with message 'Undefined index: iban' in /www/web/firefly-iii/app/Repositories/Account/AccountRepository.php:492

seems like the account repository expects an IBAN number. But there is no input field for IBAN.
I'd like to try fix this bug. (using pull request), but there are 2 ways:
1) input field on the initial new-user page
2) blank input field (NULL) so users can edit it later.

What way is preferred => where can I find "documentation" about the general Idea?

kind regards,
Ronald

**Comment by RonaldvanMeer** [comment]
Now as I'm overthinking this.
IBAN is an Identification Number, specific for European countries.
Wouldn't it be better to call it "Bank account number" and making it SEPA independant? (allowing users outside Europe to use this system)
List of countries participating SEPA / IBAN (dutch website) https://www.overopiban.nl/faq-bedrijf/welke-landen-doen-mee-aan-sepa/
You could introduce a pull down menu beneath the Account number and store information like type of bankaccount number (IBAN / FedWire / ABA / General )
each of these should unlock a checking mechanism on the Account number field, checking if the account number is valid.

**Comment by JC5** [comment]
Hi!

Yes, that's a nice bug you've found there! I'd like to keep the "new user" page as simple as possible, so the best way to fix this would be to update the [NewUserController](https://github.com/JC5/firefly-iii/blob/develop/app/Http/Controllers/NewUserController.php#L54) on line 54, 70 and 87.

```'iban' => null,```

As for the bank number, I'll have to think about it. For now, I'm going to leave it as is. But your suggestions are valid, and the IBAN nummer is too "local".

**Comment by JC5** [comment]
Fixed!
