### ISSUE TITLE
Amount columns not optimized

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#95]
The 'amount' column is not optimised for a amount of 10.000,- and higher. The number is pushed on the next row below the currency symbol.

**Comment by JC5** [comment]
Which page?

**Comment by xzaz** [comment]
The reports page

**Comment by JC5** [comment]
Ah yes, found it. Has to do with the width of the page and your browser reorganising the data in the available space. I've added a nonbreaking space that should fix it.

**Comment by JC5** [comment]
Fixed.
