### ISSUE TITLE
Remove money from piggybank gives 0

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#97]
When you remove money from a piggybank the list of transactions within that piggybank tells you the money you removed is 0. 

![piggy](https://cloud.githubusercontent.com/assets/2311499/8901133/9a0686f4-3446-11e5-92ba-a091cf6da350.png)

**Comment by JC5** [comment]
Correct. Should be fixed in the next version, and properly translated as well.

**Comment by JC5** [comment]
Fixed in the current version.
