### ISSUE TITLE
Category negative vs positive

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#99]
In the list of transaction from a categroy there can be deposits and withdraws. The diagram does not make any difference between deposits and withdraws. If there is one day that contains both (a withdraw and a deposit) the numbers are just added.

**Comment by JC5** [comment]
I saw it. Am looking into it; the library I'm using now draws butt-ugly negative bar charts.

**Comment by xzaz** [comment]
Can you add totals to the categories transaction list. A sum of the total transactions?

**Comment by JC5** [comment]
Sounds like a good idea!

**Comment by JC5** [comment]
https://github.com/JC5/firefly-iii/releases/tag/3.4.11
